-- Add the 7H4 Google Sites scraper as a new source and link it to the
-- existing 7h4 kennel. Closes #510 (source coverage gap) and enables
-- #508 / #509 / #511 to be addressed via the enriched data this adapter
-- emits.
--
-- Seed file (prisma/seed-data/sources.ts) is updated in the same PR so
-- fresh installs reproduce. Per convention `prisma db seed` is never run
-- against prod; production data drifts via SQL one-shots like this.

-- 1. Insert the Source row (idempotent on name + type). `id` is normally a
-- cuid generated by the Prisma client, so we synthesize one here that is
-- unique but clearly marks its provenance.
INSERT INTO "Source" (
  id, name, url, type, enabled,
  "trustLevel", "scrapeFreq", "scrapeDays",
  "createdAt", "updatedAt"
)
SELECT
  'cmn7h4gs0000000000000a',
  'Seven Hills H3 Google Sites',
  'https://sites.google.com/view/7h4/home',
  'HTML_SCRAPER'::"SourceType",
  true,
  7,
  'daily',
  30,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM "Source" WHERE name = 'Seven Hills H3 Google Sites' AND type = 'HTML_SCRAPER'
);

-- 2. Link the new source to the 7h4 kennel (idempotent on composite unique).
INSERT INTO "SourceKennel" (id, "sourceId", "kennelId")
SELECT 'cmn7h4gssk000000000001', s.id, k.id
FROM "Source" s
JOIN "Kennel" k ON k."kennelCode" = '7h4'
WHERE s.name = 'Seven Hills H3 Google Sites'
  AND s.type = 'HTML_SCRAPER'
ON CONFLICT ("sourceId", "kennelId") DO NOTHING;

-- 3. Sanity check.
DO $$
DECLARE
  linkedCount int;
BEGIN
  SELECT COUNT(*) INTO linkedCount
  FROM "SourceKennel" sk
  JOIN "Source" s ON s.id = sk."sourceId"
  JOIN "Kennel" k ON k.id = sk."kennelId"
  WHERE s.name = 'Seven Hills H3 Google Sites'
    AND k."kennelCode" = '7h4';
  IF linkedCount = 0 THEN
    RAISE EXCEPTION 'Seven Hills H3 Google Sites source → 7h4 kennel link did not land';
  END IF;
END $$;
