-- Clear the contaminated hares value on Tokyo H3 Run #2578 (#521).
-- The event's only RawEvent attribution is the "Singapore Sunday H3 Harrier
-- Central" source, which is now configured to fetch only Singapore events —
-- so the stale Tokyo RawEvent won't be regenerated by a re-scrape, and the
-- adapter fix in PR #533 can't propagate to this specific canonical row.
-- Manual clean-up is the pragmatic path.
--
-- The kennel owner typed "JR Keihintohoku line" (a train line name) into
-- both the hares and location slots on hashruns.org. The adapter's
-- duplicate-field guard would null the hares on a re-scrape; this one-shot
-- applies the same outcome directly.

UPDATE "Event"
SET "haresText" = NULL,
    "updatedAt" = NOW()
WHERE id = 'cmnf1jx5b000404ibszgi147j'
  AND "haresText" = 'JR Keihintohoku line';

DO $$
DECLARE
  stored text;
BEGIN
  SELECT "haresText" INTO stored FROM "Event" WHERE id = 'cmnf1jx5b000404ibszgi147j';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Tokyo H3 2578 event row not found — refusing to silently no-op';
  END IF;
  IF stored IS NOT NULL THEN
    RAISE EXCEPTION 'Tokyo H3 2578 haresText did not clear: %', stored;
  END IF;
END $$;
