-- Kennel profile + weekend-schedule corrections the null-fill seed cannot apply.
--
-- prisma/seed.ts `ensureKennelRecords` only fills profile fields on an existing
-- kennel when the DB value is NULL ("don't overwrite existing values"), so a
-- value CHANGE to an already-non-null field never reaches prod via
-- `prisma db seed`. Vercel runs `prisma migrate deploy` (never `db seed`), so
-- these corrections are applied here. prisma/seed-data/kennels.ts carries the
-- matching values, so a fresh-DB seed creates the same shape. See PR #2250 /
-- issues #2240, #2226, #2210.
--
-- All statements are idempotent (IS DISTINCT FROM guards), so re-applying on an
-- already-corrected DB is a no-op.

-- #2240 Seoul H3: logoUrl was a self-hosted relative path ("/kennel-logos/sh3-kr.png")
-- with no backing file, so the kennel rendered with no logo. Point at the verified
-- absolute logo (200, image/png).
UPDATE "Kennel"
SET "logoUrl" = 'https://seoulhash.com/images/shhh_logo_120.png'
WHERE "kennelCode" = 'sh3-kr'
  AND "logoUrl" IS DISTINCT FROM 'https://seoulhash.com/images/shhh_logo_120.png';

-- #2226 San Diego H3: the scraped sdh3.com hareline runs are weekend Saturday/Sunday
-- trails (day varies week to week), not the home-page grid's "Friday". Switch to
-- weekend-varies so the schedule-rule backfill (Pass 2) derives LOW biweekly
-- "possible activity" sentinels instead of a wrong weekly-Friday rule. Drop the
-- Friday-only 6:30 PM time.
UPDATE "Kennel"
SET "scheduleDayOfWeek" = 'Saturday / Sunday',
    "scheduleTime" = NULL,
    "scheduleFrequency" = 'Biweekly',
    "scheduleNotes" = 'Weekend trails on Saturday or Sunday (day varies week to week); Sunday runs typically 10:00 AM.'
WHERE "kennelCode" = 'sdh3'
  AND (
    "scheduleDayOfWeek" IS DISTINCT FROM 'Saturday / Sunday'
    OR "scheduleTime" IS NOT NULL
    OR "scheduleFrequency" IS DISTINCT FROM 'Biweekly'
  );

-- #2210 Morgantown H3: irregular weekend kennel (Saturday/Sunday varies, ~0.5
-- trails/week + weeknight specials). The weekly-Saturday rule drifted against the
-- Sunday-leaning actuals. Switch to weekend-varies so Pass 2 derives LOW biweekly
-- sentinels — clears the drift without over-projecting two trails every week.
UPDATE "Kennel"
SET "scheduleDayOfWeek" = 'Saturday / Sunday',
    "scheduleFrequency" = 'Biweekly',
    "scheduleNotes" = 'Weekend trails on Saturday or Sunday (day varies week to week), plus weeknight full-moon and themed runs. Watch the calendar for what''s next.'
WHERE "kennelCode" = 'mh3-wv'
  AND (
    "scheduleDayOfWeek" IS DISTINCT FROM 'Saturday / Sunday'
    OR "scheduleFrequency" IS DISTINCT FROM 'Biweekly'
  );

-- Deactivate the stale wrong-weekday autogenerated rules so the corrections take
-- effect on deploy: Travel Mode and the weekly rule-drift cron read ScheduleRule
-- directly. The next `prisma db seed` Pass 2 re-derives LOW Sat/Sun sentinels from
-- the corrected flat fields above (reads the DB, not kennels.ts, so even a seed
-- from a stale worktree converges correctly); until then these kennels project
-- nothing and their real source events still drive actual trails.
UPDATE "ScheduleRule" sr
SET "isActive" = false, "updatedAt" = NOW()
FROM "Kennel" k
WHERE sr."kennelId" = k.id
  AND sr.source::text = 'SEED_DATA'
  AND sr."isActive" = true
  AND (
    (k."kennelCode" = 'sdh3' AND sr.rrule = 'FREQ=WEEKLY;BYDAY=FR')
    OR (k."kennelCode" = 'mh3-wv' AND sr.rrule = 'FREQ=WEEKLY;BYDAY=SA')
  );
