-- Issue #1415: GM, hare raiser, signature event, founder, parent kennel on Kennel.
--
-- Chrome-kennel audits keep surfacing these recurring profile fields
-- (e.g. Humpin' SD GM "Titty Kitty", GyNO H3 founder "Wrap It Up",
-- parent kennel "Memphis H3") but there's nowhere to persist them today,
-- so audit-discovered data gets lost. This migration adds five nullable
-- TEXT columns that the seed merge (PROFILE_FIELDS in prisma/seed.ts)
-- and the admin KennelForm both populate.
--
-- parentKennelCode holds the kennelCode of the sponsoring/parent kennel
-- (not a Prisma relation) so we can reference kennels that may not yet
-- exist in our database without violating FK constraints. The UI looks
-- the parent up by kennelCode and falls back to raw text on miss.
--
-- All five are nullable — kennels without audit-curated data leave them
-- null and render unchanged.
--
-- Hand-authored: `prisma migrate dev` couldn't run a shadow-DB pass
-- because pending migration `20260504010411_kennel_profile_bundle...`
-- has a kennelCode existence guard that fails on an empty shadow DB
-- (same blocker hit by #1316 / #1266 / #890 — diff was generated by
-- inspecting the schema change against existing optional-string columns).

ALTER TABLE "Kennel" ADD COLUMN     "gm" TEXT,
ADD COLUMN     "hareRaiser" TEXT,
ADD COLUMN     "signatureEvent" TEXT,
ADD COLUMN     "founder" TEXT,
ADD COLUMN     "parentKennelCode" TEXT;
