import { describe, it, expect } from "vitest";
import { isDefaultTitleShape } from "./backfill-event-titles";

describe("isDefaultTitleShape", () => {
  const greyIds = ["bristol-grey", "GREY", "Bristol Greyhound Hash", "Greyhound Hash"];

  it.each([
    ["GREY Trail", true],
    ["GREY Trail #42", true],
    ["bristol-grey Trail", true],
    ["bristol-grey Trail #1357", true],
    ["  GREY Trail  ", true], // trim-tolerant
    ["grey trail", true], // case-insensitive
  ])("returns true for autogenerated shape %s", (title, expected) => {
    expect(isDefaultTitleShape(title, greyIds)).toBe(expected);
  });

  it.each([
    ["GREY Trail to the Brewery", false], // custom suffix
    ["GREY Trail #42 - Halloween Hash", false], // custom suffix after run number
    ["Le Caniveau's Birthday Hash", false], // no kennel prefix
    ["GREY Run", false], // not "Trail"
    ["GREY", false], // missing "Trail"
    ["Trail", false], // missing identifier
    ["Bristol Greyhound H3 Trail", false], // already canonical, doesn't match aliases
  ])("returns false for non-default-shape title %s", (title, expected) => {
    expect(isDefaultTitleShape(title, greyIds)).toBe(expected);
  });

  it("handles empty identifier list", () => {
    expect(isDefaultTitleShape("GREY Trail", [])).toBe(false);
  });

  it("ignores empty/whitespace identifiers in the list", () => {
    expect(isDefaultTitleShape("GREY Trail", ["", "  ", "GREY"])).toBe(true);
  });

  it("does not match autogenerated-style title with extra trailing content beyond run number", () => {
    expect(isDefaultTitleShape("GREY Trail #42 extra", greyIds)).toBe(false);
  });
});
