/**
 * One-time backfill: rewrite stale autogenerated default titles that use a
 * raw kennelCode/alias prefix instead of the kennel's display name.
 *
 * Conservative match: only rewrites titles whose entire body is the synthesis
 * shape `<identifier> Trail` or `<identifier> Trail #<n>` (case-insensitive,
 * trim-tolerant). Custom titles like `GREY Trail to the Brewery` stay
 * untouched — they have meaningful suffix content the on-insert rewrite
 * preserves but a one-shot backfill should not change irreversibly.
 *
 * For the matched rows the actual rewrite delegates to `rewriteStaleDefaultTitle`
 * so the canonical form stays in lockstep with the on-insert path.
 *
 * Usage:
 *   npx tsx scripts/backfill-event-titles.ts          # dry run (default)
 *   npx tsx scripts/backfill-event-titles.ts --apply  # apply changes
 */
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";
import { rewriteStaleDefaultTitle } from "../src/pipeline/merge";
import { createScriptPool } from "./lib/db-pool";

const dryRun = !process.argv.includes("--apply");

/** Matches the autogenerated default-title shape: "<id> Trail" or "<id> Trail #N" — and nothing more. */
export function isDefaultTitleShape(title: string, identifiers: string[]): boolean {
  const trimmed = title.trim();
  for (const id of identifiers) {
    if (!id) continue;
    const escaped = id.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`);
    if (new RegExp(String.raw`^${escaped}\s+Trail(?:\s+#\d+)?$`, "i").test(trimmed)) {
      return true;
    }
  }
  return false;
}

async function main() {
  const pool = createScriptPool();
  const adapter = new PrismaPg(pool);
  const prisma = new PrismaClient({ adapter } as never);

  console.log(dryRun ? "🔍 DRY RUN — no changes will be made\n" : "✏️  APPLYING changes\n");

  const kennels = await prisma.kennel.findMany({
    select: {
      id: true,
      kennelCode: true,
      shortName: true,
      fullName: true,
      aliases: { select: { alias: true } },
    },
  });

  let totalRewritten = 0;
  let kennelsTouched = 0;

  for (const k of kennels) {
    // Only events whose title is non-null have any chance of being stale —
    // null-title events are synthesized at read time and aren't drift.
    const events = await prisma.event.findMany({
      where: { kennelId: k.id, title: { not: null } },
      select: { id: true, title: true },
    });

    const aliases = k.aliases.map((a) => a.alias);
    const identifiers = [k.kennelCode, k.shortName, ...aliases].filter(Boolean);
    const stale: { id: string; oldTitle: string; newTitle: string }[] = [];
    for (const ev of events) {
      if (!ev.title) continue;
      // Conservative: only touch rows whose title IS the autogenerated shape.
      // A title like "GREY Trail to the Brewery" is meaningful custom content
      // and stays untouched here even though the on-insert rewrite would
      // canonicalize the prefix.
      if (!isDefaultTitleShape(ev.title, identifiers)) continue;
      const next = rewriteStaleDefaultTitle(ev.title, k.kennelCode, k.shortName, k.fullName, aliases);
      if (next !== ev.title) {
        stale.push({ id: ev.id, oldTitle: ev.title, newTitle: next });
      }
    }

    if (stale.length === 0) continue;
    kennelsTouched++;
    console.log(`\n${k.kennelCode} (${k.shortName}): ${stale.length} event(s) to rewrite`);
    for (const s of stale.slice(0, 5)) {
      console.log(`  ${s.id}: "${s.oldTitle}" → "${s.newTitle}"`);
    }
    if (stale.length > 5) {
      console.log(`  ... and ${stale.length - 5} more`);
    }

    if (!dryRun) {
      // Batch updates per kennel to keep the connection pool happy.
      for (const s of stale) {
        await prisma.event.update({ where: { id: s.id }, data: { title: s.newTitle } });
      }
    }
    totalRewritten += stale.length;
  }

  console.log(
    `\n${dryRun ? "Would rewrite" : "Rewrote"} ${totalRewritten} event title(s) across ${kennelsTouched} kennel(s).`,
  );
  if (dryRun && totalRewritten > 0) {
    console.log("Run with --apply to make changes.");
  }

  await prisma.$disconnect();
  pool.end();
}

// Only run when invoked directly (not when imported by tests).
const isEntrypoint =
  typeof process !== "undefined" &&
  import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isEntrypoint) {
  main().catch((err) => {
    console.error("Fatal error:", err);
    process.exit(1);
  });
}
