/**
 * Inspect Hebe H3 (`hebe-h3`) for ORPHAN synthetic events that were generated
 * by the STATIC_SCHEDULE adapter on the wrong dates.
 *
 * Background (#1388 + #1390):
 *   The Hebe seed shipped with `rrule: "FREQ=MONTHLY;BYDAY=SA;BYSETPOS=3"` for
 *   ~year. The in-repo `parseRRule` SILENTLY IGNORED `BYSETPOS` and fell through
 *   to "first Saturday of month" generation — which is the cadence Hebe actually
 *   runs on (verified via FB Run #78 on Apr 4, 2026 = a 1st Saturday). So the
 *   misleading RRULE was masked by the parser bug and never produced wrong-date
 *   events. PR #1405 fixed the parser (now rejects BYSETPOS); PR #1406 fixed
 *   the seed RRULE to the canonical `BYDAY=1SA`.
 *
 *   Expected result of this script: ZERO orphan candidates. The seed change is
 *   semantically a no-op for event generation. If it returns >0 we need to
 *   investigate before applying any cleanup.
 *
 * This is a DRY-RUN-ONLY script. It identifies candidate orphans (Hebe past
 * events on dates that aren't 1st Saturdays) and prints them. It does NOT
 * delete anything. If a non-empty set ever surfaces, the cleanup pass should
 * use `scripts/lib/cascade-delete.ts` (`cascadeDeleteEvents`) which mirrors
 * the admin `deleteEventsCascade` semantics.
 *
 * Usage:
 *   npx tsx scripts/inspect-hebe-orphan-synthetic-events.ts
 */
import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@/generated/prisma/client";
import { createScriptPool } from "./lib/db-pool";

const HEBE_KENNEL_CODE = "hebe-h3";

/**
 * Is the given UTC-noon date the first Saturday of its calendar month?
 */
function isFirstSaturdayOfMonth(d: Date): boolean {
  if (d.getUTCDay() !== 6) return false; // not Saturday
  return d.getUTCDate() <= 7; // any Saturday in days 1–7 is the 1st
}

async function main() {
  const pool = createScriptPool();
  const prisma = new PrismaClient({ adapter: new PrismaPg(pool) });

  try {
    const kennel = await prisma.kennel.findUnique({
      where: { kennelCode: HEBE_KENNEL_CODE },
      select: { id: true, shortName: true },
    });
    if (!kennel) {
      console.error(`✗ Kennel "${HEBE_KENNEL_CODE}" not found.`);
      process.exitCode = 1;
      return;
    }

    const now = new Date();
    const todayUtc = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate(), 12, 0, 0));

    // All past events for Hebe. We look at past-only because future events
    // are still authoritatively regenerated by the STATIC_SCHEDULE source on
    // each scrape — any drift there self-heals. Past events would be the
    // permanently-orphaned set.
    const events = await prisma.event.findMany({
      where: {
        eventKennels: { some: { kennelId: kennel.id } },
        date: { lt: todayUtc },
        status: "CONFIRMED",
      },
      orderBy: { date: "asc" },
      select: { id: true, date: true, title: true, isManualEntry: true },
    });

    console.log(`━━━ Hebe H3 (${kennel.shortName}) past-event audit ━━━`);
    console.log(`  Total past CONFIRMED events: ${events.length}`);

    const orphanCandidates = events.filter(
      (e) => !e.isManualEntry && !isFirstSaturdayOfMonth(e.date),
    );

    console.log(`  Orphan candidates (non-1st-Saturday, non-manual): ${orphanCandidates.length}`);

    if (orphanCandidates.length === 0) {
      console.log(`  ✓ No orphans — seed RRULE fix is semantically a no-op.`);
      console.log(`    (Parser silently ignored BYSETPOS=3, generated 1st Saturdays anyway.)`);
      return;
    }

    console.log(`\n  ⚠ ${orphanCandidates.length} candidate(s) found — investigate before cleanup:\n`);
    for (const e of orphanCandidates.slice(0, 20)) {
      console.log(`    ${e.date.toISOString().slice(0, 10)}  ${e.id}  ${e.title ?? "(no title)"}`);
    }
    if (orphanCandidates.length > 20) {
      console.log(`    ... and ${orphanCandidates.length - 20} more`);
    }
    console.log(
      "\n  If after investigation these are confirmed wrong-date orphans, " +
        "cleanup uses scripts/lib/cascade-delete.ts → cascadeDeleteEvents(prisma, ids).",
    );
  } catch (err) {
    console.error(err);
    process.exitCode = 1;
  } finally {
    await Promise.allSettled([prisma.$disconnect(), pool.end()]);
  }
}

void main();
