// ── ALIAS DATA (PRD Appendix D.3) ──

// Aliases keyed by kennelCode (matches kennelRecords keys)
export const KENNEL_ALIASES: Record<string, string[]> = {
    "nych3": ["NYC", "HashNYC", "NYC Hash", "NYCH3", "New York Hash", "NYC H3"],
    "boh3": ["Boston", "BH3", "BoH3", "Boston Hash"],
    "brh3": ["Brooklyn", "BrH3", "Brooklyn Hash", "Brooklyn H3"],
    "bobbh3": ["Ballbuster", "BoBBH3", "Boston Ballbuster", "Ballbuster Hash", "B3H4", "Boston Ballbuster Hardcore", "Boston Ballbuster H4"],
    "nawwh3": ["NAWW", "NAWWH3", "NAWW Hash"],
    "nah3": ["New Amsterdam", "NAH3", "NASS", "New Amsterdam Hash"],
    "qbk": ["Queens Black Knights", "QBK", "QBK Hash", "Queens", "Queens Hash"],
    "lil": ["Long Island Lunatics", "LIL", "Long Island", "LI Hash", "Lunatics"],
    "bfm": ["Ben Franklin Mob", "BFM", "BFM H3", "BFMH3"],
    "philly-h3": ["Philly Hash", "Philly H3", "Philadelphia H3", "Philadelphia Hash", "hashphilly"],
    "bos-moon": ["Moon", "Moom", "Boston Moon", "Bos Moon", "Bos Moom", "Boston Moon H3", "Boston Moon Hash"],
    "pink-taco": ["Pink Taco", "Pink Taco Hash", "PT2H3", "Pink Taco Trotters"],
    "beantown": ["Beantown", "Beantown Hash", "Beantown City", "Beantown City H3", "Beantown City Hash"],
    "knick": ["Knick", "Knickerbocker", "Knickerbocker Hash"],
    "columbia": ["Columbia", "Columbia Hash"],
    "ggfm": ["GGFM", "GGFM Hash"],
    "harriettes-nyc": ["Harriettes", "Harriettes Hash", "Harriettes (NYC)", "Harriettes NYC"],
    "si": ["Staten Island", "SI", "SI Hash", "Staten Island Hash"],
    "drinking-practice-nyc": ["Drinking Practice", "NYC Drinking Practice", "NYC DP", "DP"],
    // Upstate New York
    "soh4": ["SOH4", "Syracuse Hash", "Syracuse On On Dog A", "Syracuse On-On-Dog-A", "SOOD"],
    "halvemein": ["Halve Mein", "HMHHH", "Albany Hash", "Albany HHH", "Capital District Hash", "Halve Mein Hash"],
    "ih3": ["IH3", "Ithaca Hash", "Ithaca HHH", "Ithaca H3"],
    "flour-city": ["Flour City", "FCH3", "FCHHH", "Flour City Hash", "Rochester Hash", "Flour City HHH"],
    "bh3": ["BH3", "Buffalo Hash", "Hash in the Buff", "Buffalo HHH"],
    "hvh3-ny": ["HVH3 NY", "Hudson Valley Hash", "HV H3", "Hudson Valley HHH", "HVH3"],
    // Pennsylvania (outside Philly)
    "pgh-h3": ["PGH H3", "Pittsburgh Hash", "PGH", "Pittsburgh HHH"],
    "ich3": ["ICH3", "Iron City Hash", "Iron City", "Iron City HHH"],
    "nvhhh": ["NVHHH", "Nittany Valley Hash", "Nittany Valley", "NV Hash", "State College Hash"],
    "lvh3": ["LVH3", "Lehigh Valley Hash", "Lehigh Valley HHH"],
    "rh3": ["RH3", "Reading Hash", "Reading HHH"],
    "h5-hash": ["H5", "Harrisburg Hash", "Harrisburg-Hershey Hash", "H5 Hash", "Hershey Hash"],
    // Delaware
    "hockessin": ["Hockessin", "H4", "Hockessin Hash", "Hockessin HHH"],
    // Virginia (outside DC metro)
    "rvah3": ["RH3", "RVAH3", "Richmond Hash", "Richmond HHH", "RVA Hash"],
    "feh3": ["FEH3", "Fort Eustis Hash", "Fort Eustis", "Ft Eustis Hash", "Fort Eustis HHH"],
    "bdsmh3": ["BDSMH3", "BDSM Hash", "Bad Decisions Hash", "Bad Decisions Start Monday"],
    "cvilleh3": ["CvilleH3", "Charlottesville Hash", "Harlots", "cHARLOTtesville Hash", "Cville Hash"],
    "twh3": ["TH3", "Tidewater Hash", "Tidewater", "Tidewater HHH", "TH3 VA"],
    "7h4": ["7H4", "Seven Hills Hash", "Seven Hills", "7 Hills Hash"],
    // North Carolina
    "swh3": ["SWH3", "Sir Walter's", "Sir Walters", "Sir Walter's Hash", "Sir Walters Hash"],
    "larrikins": ["Larrikins", "Carolina Larrikins", "CLH3", "Larrikins H3"],
    "ch3-nc": ["CH3 NC", "Charlotte Hash", "Charlotte HHH", "Charlotte H3", "CH3"],
    "avlh3": ["AVLH3", "Asheville Hash", "AVL Hash", "Asheville HHH"],
    "cfh3": ["CFH3", "Cape Fear Hash", "Cape Fear", "Cape Fear HHH"],
    "ctrh3": ["CTrH3", "Carolina Trash", "Carolina Trash Hash", "Fayetteville Hash"],
    // Vermont
    "vth3": ["Von Tramp", "Von Tramp H3", "VTH3", "VT Hash"],
    "burlyh3": ["Burlington Hash", "Burlington H3", "BH3 Vermont", "BTVHHH", "BTV H3", "BTVH3"],
    // Connecticut
    "narwhal-h3": ["Narwhal", "Narwhal H3", "Narwhal Hash", "NarH3"],
    "sbh3-ct": ["Skull & Boners", "Skull and Boners", "SBH3", "S&B H3", "Skull Boners"],
    "rgh3": ["Rotten Groton", "Rotten Groton H3", "Groton H3", "Groton Hash", "RGH3"],
    // Rhode Island
    "rih3": ["RIH3", "Rhode Island Hash", "RI H3", "RI Hash", "Rhode Island HHH"],
    // Ohio
    "dh4": ["DH4", "DH3", "Dayton H4", "Dayton H3", "Dayton Hash", "Dayton HHH"],
    "mvh3-day": ["MVH3", "Miami Valley H3", "Miami Valley Hash"],
    "swot-h3": ["SWOT", "SWOT H3", "South West Ohio Traditional"],
    "sch4": ["SCH4", "Sin City H4", "Sin City Hash", "Cincinnati Hash"],
    "qch4": ["QCH4", "QCH3", "Queen City H4", "Queen City Hash"],
    "lvh3-cin": ["LVH3", "Licking Valley H3", "Licking Valley Hash"],
    "cleh4": ["CleH4", "Cleveland H4", "Cleveland Hash", "Cleveland H3"],
    "rch3": ["RCH3", "Rubber City H3", "Rubber City Hash", "Akron Hash", "RCH3-OH"],
    "renh3": ["RH3", "Renegade H3", "Renegade Hash", "RH3 Columbus", "RH3C"],
    // Massachusetts
    "hvh3": ["HVH3", "Happy Valley", "Happy Valley H3", "HV H3"],
    "413h3": ["413H3", "413 H3"],
    "zigzag": ["ZigZag", "Zig Zag", "Zig-Zag", "ZZH3", "Zig Zag H3"],
    "e4b": ["E4B", "E4BH3", "Eager4Beaver", "Eager 4 Beaver", "Eager 4 Beaver H3"],
    "nbh3": ["NbH3", "Northboro H3", "BS Hash", "Boston Suburbs Hash", "BSH3", "Northboro"],
    "poofh3": ["PooFH3", "PooFlingers", "Poo Flingers", "PooF", "PooF H3"],
    "summit": ["Summit", "Summit H3", "Summit Hash", "SH3"],
    "sfm": ["SFM", "SFM H3", "Summit Full Moon", "Summit Full Moon H3"],
    "asssh3": ["ASSSH3", "ASSS H3", "All Seasons Summit Shiggy"],
    "rumson": ["RH3", "Rumson H3", "Rumson Hash", "Rumson HHH"],
    // Chicago area
    "ch3": ["Chicago Hash", "Chicago H3", "CHH3", "CH3"],
    "th3": ["Thirstday", "Thirstday Hash", "Thirstday H3", "Thursday Hash", "TH3"],
    "cfmh3": ["Chicago Full Moon", "Chicago Full Moon Hash", "Chicago Moon Hash"],
    "fcmh3": ["First Crack", "First Crack H3", "First Crack of the Moon", "New Moon Hash"],
    "bdh3": ["Big Dogs", "Big Dogs H3", "Big Dogs Hash"],
    "bmh3": ["Bushman", "Bushman H3", "Bushman Hash", "The Greatest Hash", "BMH3"],
    "2ch3": ["Second City", "Second City H3", "Second City Hash"],
    "wwh3": ["Whiskey Wednesday", "Whiskey Wednesday Hash", "WWW H3"],
    "4x2h4": ["4x2 H4", "Four by Two H4", "4x2 Hash", "Four by Two"],
    "rth3": ["Ragtime", "Ragtime Hash", "Brunch Hash"],
    "dlh3": ["Duneland", "Duneland H3", "South Shore HHH"],
    // DC / DMV area
    "ewh3": ["Everyday is Wednesday", "Every Day is Wednesday"],
    "shith3": ["SHIT H3", "S.H.I.T. H3", "So Happy It's Tuesday"],
    "cch3": ["Charm City", "Charm City Hash", "Charm City H3", "CCH3"],
    "w3h3": ["Wild and Wonderful Wednesday"],
    "dch4": ["DC Harriettes", "DC Harriettes and Harriers", "Harriettes and Harriers"],
    "wh4": ["White House Hash", "White House H3", "White House"],
    "bah3": ["Baltimore Annapolis", "Baltimore Annapolis Hash"],
    "mvh3": ["Mount Vernon Hash", "Mount Vernon H3", "Mount Vernon"],
    "ofh3": ["Old Frederick", "Old Frederick Hash"],
    "dcfmh3": ["DC Full Moon", "DC Full Moon Hash"],
    "gfh3": ["Great Falls", "Great Falls Hash"],
    "dch3": ["DC Hash", "DC Hash House Harriers", "the Men's Hash"],
    "oth4": ["Over the Hump"],
    "smuttycrab": ["SMUTTy Crab", "SMUTT", "Smutty Crab H3"],
    "hillbillyh3": ["Hillbilly Hash", "Hillbilly H3"],
    "dcrt": ["DC Red Tent", "Red Tent H3", "Red Tent Harriettes"],
    "h4": ["Hangover Hash", "Hangover H3", "Hangover", "H4"],
    "fuh3": ["Fredericksburg Urban Hash", "FXBG H3"],
    "dcph4": ["DC Powder Pedal Paddle"],
    // San Francisco Bay Area
    "sfh3": ["SF Hash", "San Francisco Hash", "San Francisco H3", "SF H3"],
    "gph3": ["Gypsies", "Gypsies H3", "Gypsies in the Palace", "GIP H3", "Gypsies Hash"],
    "ebh3": ["East Bay", "East Bay Hash", "East Bay H3", "EB Hash"],
    "svh3": ["Silicone Valley", "Silicone Valley H3", "Silicon Valley Hash", "SV Hash"],
    "fhac-u": ["FHACU", "FHAC-U H3", "FHAgnews"],
    "agnews": ["Agnews H3", "Agnews State H3", "Agnews Hash"],
    "barh3": ["Bay Area Rabble", "BAR H3"],
    "marinh3": ["Marin Hash", "Marin H3", "Marin HHH"],
    "fch3": ["Fog City", "Fog City Hash", "Fog City H3"],
    "sffmh3": ["SF Full Moon", "SF Full Moon Hash", "FMH3", "Full Moon H3 (SF)"],
    "vmh3": ["Vine & Malthouse", "Vine and Malthouse H3"],
    "mwh3": ["Muir Woods H3", "Muir Woods Hash", "Muir Woods"],
    "262h3": ["Marathon Hash", "Marathon H3", "26.2 Hash"],
    // London, UK
    "lh3": ["London Hash", "London H3", "London Hash House Harriers", "LH3"],
    "cityh3": ["City Hash", "City H3"],
    "wlh3": ["West London Hash", "West London H3", "WLH"],
    "barnesh3": ["Barnes Hash", "Barnes H3"],
    "och3": ["Old Coulsdon", "Old Coulsdon Hash", "OC Hash"],
    "slh3": ["SLASH", "SLAH3", "South London Hash"],
    "fukfm": ["FUKFMH3", "FUK Full Moon", "First UK Full Moon"],
    "eh3": ["Enfield Hash", "Enfield H3", "EH3"],
    "ch4": ["Catch the Hare", "CTH"],
    "cunth3": ["CUNT H3", "Currently Unnamed North Thames"],
    // Ireland
    "dh3": ["Dublin H3", "Dublin HHH", "Dublin Hash", "DH3", "I Love Monday"],
    // Texas
    "ah3": ["Austin Hash", "Austin H3", "AH3", "Austin HHH"],
    "kawh3": ["Keep Austin Weird", "KAW!H3", "KAW H3", "KAWH3", "Keep Austin Weird Hash"],
    "h4-tx": ["Houston Hash", "Houston H3", "H4 Houston", "Houston HHH", "H-Town Hash", "H4"],
    "bmh3-tx": ["Brass Monkey", "Brass Monkey H3", "Brass Monkey Hash", "Team Brass Monkey"],
    "mosquito-h3": ["Mosquito Hash", "Mosquito H3", "Mosquito HHH"],
    "dh3-tx": ["Dallas Hash", "Dallas H3", "DH3 Dallas", "Dallas HHH", "DH3"],
    "duhhh": ["Dallas Urban Hash", "DUHHH", "DUH H3", "Dallas Urban"],
    "noduhhh": ["NODUHHH", "North Dallas Hash", "North of Dallas Urban", "NoDUHHH"],
    "fwh3": ["Fort Worth Hash", "Fort Worth H3", "FWH3", "Ft Worth Hash"],
    "sah3": ["San Antonio Hash", "San Antonio H3", "SAH3", "SA Hash"],
    "c2h3": ["Corpus Christi Hash", "Corpus Christi H3", "C2H3", "CC Hash"],
    // Florida
    "mia-h3": ["Miami Hash", "Miami H3", "Dade H3", "MH3"],
    "wildcard-h3": ["Wildcard Hash", "FTL Wildcard", "Fort Lauderdale Wildcard"],
    "h6": ["Hollyweird H6", "Hollyweird Hash", "HHHH", "Hollywood Hash"],
    "pbh3": ["Palm Beach Hash", "PB H3", "PBHHH"],
    "cbh3": ["Corned Beef Hash"],
    "tch3-fl": ["Treasure Coast Hash", "TCH3"],
    "kwh3": ["Key West Hash", "KW H3", "KWHH3"],
    "tbh3-fl": ["Tampa Bay Hash", "Tampa Hash", "TBH3"],
    "jrh3": ["Jolly Roger Hash", "Jolly Roger H3", "JR H3"],
    "sph3-fl": ["St Pete Hash", "SPH3", "St Petersburg Hash"],
    "circus-h3": ["Circus Hash", "Sarasota Hash", "CH3 Sarasota"],
    "nsah3": ["No Strings Hash", "NSA Hash"],
    "lush": ["LUSH Hash", "Sun-Coast Hashers"],
    "b2b-h3": ["Bay 2 Beaches", "B2B Hash"],
    "lh3-fl": ["Lakeland Hash", "LH3"],
    "barf-h3": ["BARF Hash", "Bay Area Frolic", "BARF H3"],
    "sbh3": ["Spring Brooks Hash", "SB H3", "SBH3"],
    "tth3-fl": ["Taco Tuesday Hash", "Taco Tuesday H3"],
    "o2h3": ["Other Orlando", "Other Orlando Hash", "O2H3 Hash", "Orlando Hash"],
    "okissme-h3": ["OKissMe Hash", "Kissimmee Hash"],
    "bvd-h3": ["BVD Hash", "Melbourne Hash", "Brevard Hash"],
    "h3sc": ["Space Coast Hash", "H3SC Hash"],
    "gatr-h3": ["GATR Hash", "Gainesville Hash", "GATRH3"],
    "dbh3": ["Daytona Hash", "Daytona Beach Hash", "DB H3"],
    "jax-h3": ["Jax Hash", "Jacksonville Hash", "Jax H3"],
    "tna-h3": ["T&A Hash", "Tally Hash", "Tallahassee Hash", "TNAH3"],
    "pch3": ["Panama City Hash", "PC H3", "PCH3"],
    "survivor-h3": ["Survivor Hash", "Pensacola Hash"],
    "ech3-fl": ["Emerald Coast Hash", "Fort Walton Hash", "FWB Hash"],
    // Georgia
    "ah4": ["Atlanta Hash", "Atlanta H4", "Atlanta HHH", "AH4 Hash", "Atlanta Hash (Saturdays)", "AHHH"],
    "ph3-atl": ["Pinelake Hash", "Pinelake H3", "PH3 ATL"],
    "bsh3": ["Black Sheep Hash", "Black Sheep H3", "BSH3 Hash"],
    "sobh3": ["Slow Old Bastards", "SOB Hash", "SOB H3", "SOBH3 Hash"],
    "mlh4": ["Moonlite Hash", "Atlanta Moonlite", "Moonlite H3", "Moonlite H4"],
    "whh3": ["Wheelhopper Hash", "Wheelhopper H3", "Mountain Bike Hash"],
    "sluth3": ["SLUT Hash", "Short Lazy Urban Thursday"],
    "duffh3": ["DUFF Hash", "DUFF H3"],
    "soco-h3": ["Southern Coven", "SoCo Hash", "SoCo H3"],
    "sch3-atl": ["Southern Comfort Hash", "Southern Comfort H3", "SCH3 ATL", "SCH3"],
    "hmh3": ["Hog Mountain Hash", "Hog Mountain H3"],
    "cunth3-atl": ["C U Next Tuesday", "CUNT Hash ATL"],
    "dsh3-atl": ["Dark Side Hash", "Dark Side H3", "DSH3 ATL"],
    "savh3": ["Savannah Hash", "SavH3", "Savannah H3", "SAV H3"],
    "pfh3": ["Peach Fuzz Hash", "Peach Fuzz H3"],
    "augh3": ["Augusta Underground", "Augusta Hash", "AUG H3"],
    "mgh4": ["Middle Georgia Hash", "Middle GA H3", "MGH4 Hash"],
    "w3h3-ga": ["Wednesday Wednesday Wednesday", "W3H3 Macon", "WWW H3 GA", "W3H3"],
    "cvh3": ["Chattahoochee Valley Hash", "Columbus Hash", "CV H3"],
    "r2h3": ["Rumblin Roman Hash", "Rome Hash", "R2H3 Hash"],
    // South Carolina
    "ch3-sc": ["Charleston Hash", "Charleston H3", "Charleston HHH", "CSCH3", "CH3"],
    "chh3": ["Charleston Heretics", "Charleston Happy Heretics", "Charleston Heretics H3", "Happy Heretics"],
    "budh3": ["Beaufort Ugly Dog", "Beaufort H3", "BUD H3"],
    "colh3": ["Columbian H3", "Columbian Hash", "Columbia H3", "Columbia Hash"],
    "sech3": ["Secession H3", "Secession Hash", "SHHH"],
    "palh3": ["Palmetto H3", "Palmetto Hash"],
    "uh3": ["Upstate H3", "Upstate Hash", "Upstate Hashers", "UHHH"],
    "goth3": ["Greenville's Other H3", "Greenville's Other Hash", "GOH3", "GothH3"],
    "lth3": ["Luna Ticks", "LunaTicks H3", "Luna Ticks Hash"],
    "gsh3": ["Grand Strand H3", "Grand Strand Hash", "Myrtle Beach H3", "Myrtle Beach Hash"],
    // ===== OREGON =====
    "n2h3": ["No Name Hash", "N2H3", "No Name H3", "N3H3", "Portland No Name"],
    "okh3": ["Kahuna Hash", "Kahuna H3", "Ka-Three-Na", "Katuna", "OKH3", "Oregon Kahuna"],
    "ph4": ["Hump Hash", "Portland Hump Hash", "Portland Humpin Hash", "PH4", "Humpin Hash"],
    "stumph3": ["Stumptown Hash", "Stumptown H3", "StumpH3", "Stump"],
    "dwh3": ["Dead Whores Hash", "Dead Whores H3", "DWH3", "DWH"],
    "oh3": ["Oregon Hash", "Oregon H3", "OH3", "OregonH3", "PDXGDRH3"],
    "swh3-or": ["SWH3"],
    "tgif": ["TGIF Hash", "TGIF H3"],
    "salemh3": ["Salem Hash", "Salem H3", "SalemH3", "SH3 Salem"],
    "cch3-or": ["Cherry City Hash", "Cherry City H3", "CCH3", "Cherry City"],
    "eh3-or": ["Eugene Hash", "Eugene H3", "EH3", "Eugene HHH", "EHHH"],
    "coh3": ["Central Oregon Hash", "Central Oregon H3", "COH3", "Bend Hash"],
    // ===== WASHINGTON =====
    "sh3-wa": ["Seattle Hash", "Seattle H3", "SH3", "WAH3"],
    "psh3": ["Puget Sound Hash", "Puget Sound H3", "PSH3"],
    "nbh3-wa": ["No Balls Hash", "No Balls H3", "NBH3", "Puget Sound No Balls"],
    "rch3-wa": ["Rain City Hash", "Rain City H3", "RCH3"],
    "seamon-h3": ["SeaMon Hash", "SeaMon H3", "Sea Monster Hash"],
    "cunth3-wa": ["CUNTh Hash", "CUNTh H3", "CUNTH3"],
    "taint-h3": ["Taint Hash", "Taint H3"],
    "seh3-wa": ["South End Hash", "South End H3", "SEH3"],
    "leapyear-h3": ["Leap Year Hash", "Leap Year H3"],
    "th3-wa": ["Tacoma Hash", "Tacoma H3", "TH3"],
    "ssh3-wa": ["South Sound Hash", "South Sound H3", "SSH3"],
    "giggity-h3": ["Giggity Hash", "Giggity H3"],
    "hswtf-h3": ["HSWTF Hash", "HSWTF H3", "Holy Shit What The Fuck"],
    // ===== COLORADO =====
    "dh3-co": ["Denver Hash", "Denver H3", "DH3", "DenverH3"],
    "mihi-huha": ["Mile High Humpin Hash", "MiHiHuHa", "Mile High H3", "MHHH3"],
    "bh3-co": ["Boulder Hash", "Boulder H3", "BH3"],
    "fch3-co": ["Fort Collins Hash", "Fort Collins H3", "FCH3", "FoCo Hash"],
    "pph4": ["Pikes Peak Hash", "Pikes Peak H3", "PPH3", "PP H3"],
    "kimchi-h3": ["Kimchi Hash", "Colorado Kimchi", "Kimchi H3"],
    "dim-h3": ["Damn Its Monday Hash", "DIM H3", "DIM Hash"],
    // ===== MINNESOTA =====
    "mh3-mn": ["Minneapolis Hash", "Minneapolis H3", "MH3", "MplsH3"],
    "t3h3": ["Twin Titties Hash", "Twin Titties Thirstday", "T3H3", "TTTH3"],
    // ===== CALIFORNIA =====
    "sch3-ca": ["Surf City Hash", "Surf City H3", "SCH3", "Santa Cruz Hash"],
    "lah3": ["Los Angeles Hash", "LAH3 Hash", "LA Hash House Harriers"],
    "lbh3": ["Long Beach Hash", "LBH3 Hash", "Long Beach H3"],
    "tdh3-lb": ["Throw Down Hash", "Throw Down H3", "TDH3"],
    "gal-h3": ["Get A Life Hash", "Get A Life H3", "GAL H3"],
    "suph3": ["Stand Up Paddling Hash", "SUP H3", "SUP-H3", "Paddle Hash"],
    "fth3": ["Foothill Hash", "Foothill H3"],
    "elah3": ["East LA Hash", "East LA H3", "East Los Angeles Hash"],
    "sgh3": ["Signal Hill Hash", "Signal Hill H3"],
    "sdh3": ["San Diego Hash", "SD Hash", "SD H3", "San Diego H3"],
    "clh3-sd": ["Larrikins Hash", "California Larrikins", "Larrikins H3", "CLH3"],
    "ljh3": ["La Jolla Hash", "La Jolla H3", "LJH3"],
    "nch3-sd": ["North County Hash", "North County H3", "NCH3"],
    "irh3-sd": ["Iron Rule Hash", "Iron Rule H3", "IRH3"],
    "humpin-sd": ["Humpin Hash", "Humpin H3", "Humpin'"],
    "fmh3-sd": ["Full Moon Hash SD", "SD Full Moon", "FMH3"],
    "hah3-sd": ["Half-Assed Hash", "Half Assed H3", "HAH3"],
    "mh4-sd": ["Mission Harriettes Hash", "Mission H4", "MH4"],
    "drh3-sd": ["Diaper Rash Hash", "Diaper Rash H3", "DRH3"],
    "ochhh": ["Orange County Hash", "OC Hash", "OCHHH", "OC H3"],
    "ochump": ["OC Hump Hash", "OC Hump H3"],
    "sloh3": ["San Luis Obispo Hash", "SLO Hash", "SLO H3", "SLOH3"],
  };

