// ── SHARED SFH3 CONFIG (used by both iCal and HTML sources) ──

const sfh3KennelPatterns: Array<[string, string]> = [
    ["^SFH3", "SFH3"],
    ["^GPH3", "GPH3"],
    ["^EBH3", "EBH3"],
    ["^SVH3", "SVH3"],
    ["^FHAgnews", "FHAC-U"],
    ["^FHAC-U", "FHAC-U"],
    ["^Agnews", "Agnews"],
    ["^Marin H3", "MarinH3"],
    ["^FCH3", "FCH3"],
    ["^FMH3", "SFFMH3"],
    ["^BARH3", "BARH3"],
    ["^VMH3", "VMH3"],
    ["^MWH3", "MWH3"],
    ["^26\\.2H3", "26.2H3"],
];

const sfh3Config = {
  kennelPatterns: sfh3KennelPatterns,
  defaultKennelTag: "SFH3",
  skipPatterns: ["^Hand Pump", "^Workday"],
};

const sfh3KennelCodes = [
  "sfh3", "gph3", "ebh3", "svh3", "fhac-u", "agnews",
  "barh3", "marinh3", "fch3", "sffmh3", "vmh3", "mwh3", "262h3",
];

// ── SOURCE DATA (PRD Section 8) ──

export const SOURCES = [
    {
      name: "HashNYC Website",
      url: "https://hashnyc.com",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      kennelCodes: ["nych3", "brh3", "nah3", "knick", "lil", "qbk", "si", "columbia", "harriettes-nyc", "ggfm", "nawwh3"],
    },
    {
      name: "Boston Hash Calendar",
      url: "bostonhash@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      kennelCodes: ["boh3", "bobbh3", "beantown", "bos-moon", "pink-taco"],
    },
    {
      name: "Summit H3 Spreadsheet",
      url: "https://docs.google.com/spreadsheets/d/1wG-BNb5ekMHM5euiPJT1nxQXZ3UxNqFZMdQtCBbYaMk",
      type: "GOOGLE_SHEETS" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 9999,
      config: {
        sheetId: "1wG-BNb5ekMHM5euiPJT1nxQXZ3UxNqFZMdQtCBbYaMk",
        columns: { runNumber: 0, specialRun: 1, date: 2, hares: 3, location: 4, title: 6, description: 9 },
        kennelTagRules: { default: "Summit", specialRunMap: { "ASSSH3": "ASSSH3" }, numericSpecialTag: "SFM" },
        startTimeRules: { byDayOfWeek: { "Mon": "19:00", "Sat": "15:00", "Fri": "19:00" }, default: "15:00" },
      },
      kennelCodes: ["summit", "sfm", "asssh3"],
    },
    {
      name: "Rumson H3 Static Schedule",
      url: "https://www.facebook.com/p/Rumson-H3-100063637060523/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Rumson",
        rrule: "FREQ=WEEKLY;BYDAY=SA",
        anchorDate: "2026-01-03",
        startTime: "10:17",
        defaultTitle: "Rumson H3 Weekly Run",
        defaultLocation: "Rumson, NJ",
        defaultDescription: "Weekly Saturday morning trail. Check Facebook for start location and hare details.",
      },
      kennelCodes: ["rumson"],
    },
    {
      name: "BFM Google Calendar",
      url: "bfmhash@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        kennelPatterns: [
          ["BFM|Ben Franklin|BFMH3", "BFM"],
          ["Philly Hash|hashphilly|Philly H3", "Philly H3"],
          ["Main Line", "Main Line H3"],
          ["TTH3", "TTH3"],
        ],
        defaultKennelTag: "BFM",
      },
      kennelCodes: ["bfm", "philly-h3"],
    },
    {
      name: "Philly H3 Google Calendar",
      url: "36ed6654c946ca632f71f400c1236c45d1bdd4e38c88c7c4da57619a72bfd7f8@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        kennelPatterns: [
          ["BFM|Ben Franklin|BFMH3", "BFM"],
          ["Philly Hash|hashphilly|Philly H3", "Philly H3"],
        ],
        defaultKennelTag: "Philly H3",
      },
      kennelCodes: ["bfm", "philly-h3"],
    },
    {
      name: "BFM Website",
      url: "https://benfranklinmob.com",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["bfm"],
    },
    {
      name: "Philly H3 Website",
      url: "https://hashphilly.com/nexthash/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["philly-h3"],
    },
    {
      name: "Chicagoland Hash Calendar",
      url: "30c33n8c8s46icrd334mm5p3vc@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        kennelPatterns: [
          ["CH3|Chicago Hash|Chicago H3", "Chicago H3"],
          ["TH3|Thirstday|Thursday Hash", "Thirstday H3"],
          ["CFMH3|Chicago Full Moon|Full Moon Hash|Full Moon H3|Moon Hash", "CFMH3"],
          ["FCMH3|First Crack", "FCMH3"],
          ["BDH3|Big Dogs", "BDH3"],
          ["BMH3|Bushman", "Bushman H3"],
          ["2CH3|Second City", "2CH3"],
          ["WWH3|Whiskey Wednesday", "WWH3"],
          ["4X2|4x2", "4X2H4"],
          ["RTH3|Ragtime", "RTH3"],
          ["DLH3|Duneland|South Shore", "DLH3"],
        ],
        defaultKennelTag: "Chicago H3",
      },
      kennelCodes: ["ch3", "th3", "cfmh3", "fcmh3", "bdh3", "bmh3", "2ch3", "wwh3", "4x2h4", "rth3", "dlh3"],
    },
    {
      name: "Chicago Hash Website",
      url: "https://chicagohash.org/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["ch3"],
    },
    {
      name: "Thirstday Hash Website",
      url: "https://chicagoth3.com/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      kennelCodes: ["th3"],
    },
    {
      name: "EWH3 Google Calendar",
      url: "ewh3harerazor@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "EWH3",
      },
      kennelCodes: ["ewh3"],
    },
    {
      name: "SHITH3 Google Calendar",
      url: "jackschitt.shit@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "SHITH3",
      },
      kennelCodes: ["shith3"],
    },
    {
      name: "SHITH3 Website",
      url: "https://shith3.com",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["shith3"],
    },
    {
      name: "W3H3 Hareline Spreadsheet",
      url: "https://docs.google.com/spreadsheets/d/19mNka1u64ZNOHS7z_EoqRIrAOdqg5HkY9Uk8u6LwAsI",
      type: "GOOGLE_SHEETS" as const,
      trustLevel: 6,
      scrapeFreq: "daily",
      scrapeDays: 9999,
      config: {
        sheetId: "19mNka1u64ZNOHS7z_EoqRIrAOdqg5HkY9Uk8u6LwAsI",
        tabs: ["W3H3 Hareline"],
        columns: { runNumber: 0, date: 1, hares: 2, location: 3, title: 4 },
        kennelTagRules: { default: "W3H3" },
        startTimeRules: { byDayOfWeek: { "Wed": "18:09" }, default: "18:09" },
        defaultTitle: "Wild & Wonderful Wednesday Trail",
      },
      kennelCodes: ["w3h3"],
    },
    // London, UK
    {
      name: "City Hash Makesweat",
      url: "https://makesweat.com/cityhash#hashes",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["cityh3"],
    },
    {
      name: "West London Hash Website",
      url: "https://westlondonhash.com/runs/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["wlh3"],
    },
    {
      name: "London Hash Run List",
      url: "https://www.londonhash.org/runlist.php",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["lh3"],
    },
    {
      name: "Barnes Hash Hare Line",
      url: "http://www.barnesh3.com/HareLine.htm",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      kennelCodes: ["barnesh3"],
    },
    {
      name: "Old Coulsdon Hash Run List",
      url: "http://www.och3.org.uk/upcoming-run-list.html",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      kennelCodes: ["och3"],
    },
    {
      name: "SLASH Run List",
      url: "https://www.londonhash.org/slah3/runlist/slash3list.html",
      type: "HTML_SCRAPER" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      kennelCodes: ["slh3"],
    },
    {
      name: "Enfield Hash Blog",
      url: "https://enfieldhash.org/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      kennelCodes: ["eh3"],
    },
    // Ireland
    {
      name: "Dublin H3 Website Hareline",
      url: "https://dublinhhh.com/hareline",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      kennelCodes: ["dh3"],
    },
    // Bay Area iCal feed (sfh3.com aggregator — ~11 kennels)
    {
      name: "SFH3 MultiHash iCal Feed",
      url: "https://www.sfh3.com/calendar.ics?kennels=all",
      type: "ICAL_FEED" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: sfh3Config,
      kennelCodes: sfh3KennelCodes,
    },
    // Bay Area HTML scraper (sfh3.com hareline — enrichment/fallback)
    {
      name: "SFH3 MultiHash HTML Hareline",
      url: "https://www.sfh3.com/runs?kennels=all",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: sfh3Config,
      kennelCodes: sfh3KennelCodes,
    },
    // DC / DMV area — iCal feeds (ai1ec WordPress plugin)
    {
      name: "Charm City H3 iCal Feed",
      url: "https://charmcityh3.com/?plugin=all-in-one-event-calendar&controller=ai1ec_exporter_controller&action=export_events&no_html=true",
      type: "ICAL_FEED" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: {
        kennelPatterns: [
          ["^CCH3", "Charm City H3"],
          ["^Trail\\s*#", "Charm City H3"],
        ],
        defaultKennelTag: "Charm City H3",
        titleHarePattern: "~\\s*(.+)$",
      },
      kennelCodes: ["cch3"],
    },
    {
      name: "BAH3 iCal Feed",
      url: "https://www.bah3.org/?plugin=all-in-one-event-calendar&controller=ai1ec_exporter_controller&action=export_events&no_html=true",
      type: "ICAL_FEED" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: {
        defaultKennelTag: "BAH3",
        // BAH3 uses emoji-prefixed labels: "🎯 Hares (loud and clear):" and "Where:addr"
        harePatterns: [String.raw`(?:^|\n)\s*[^\n]*Hares?[^:]*:\s*(.+?)(?:\n|$)`],
        locationPatterns: [String.raw`(?:^|\n)\s*Where\s*:?\s*(.+?)(?:\n|$)`],
      },
      kennelCodes: ["bah3"],
    },
    // DC / DMV area — HTML scraper sources
    {
      name: "EWH3 WordPress Trail News",
      url: "https://www.ewh3.com/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["ewh3"],
    },
    {
      name: "DCH4 WordPress Trail Posts",
      url: "https://dch4.org/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["dch4"],
    },
    {
      name: "OFH3 Blogspot Trail Posts",
      url: "https://www.ofh3.com/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      kennelCodes: ["ofh3"],
    },
    {
      name: "Hangover H3 DigitalPress Blog",
      url: "https://hangoverhash.digitalpress.blog/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      kennelCodes: ["h4"],
    },
    // Hash Rego (hashrego.com — multi-kennel registration platform)
    {
      name: "Hash Rego",
      url: "https://hashrego.com/events",
      type: "HASHREGO" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        kennelSlugs: ["BFMH3", "EWH3", "WH4", "GFH3", "Chicago H3", "DCH4", "DCFMH3", "FCH3", "OregonH3"],
      },
      kennelCodes: ["bfm", "ewh3", "wh4", "gfh3", "ch3", "dch4", "dcfmh3", "fch3", "oh3"],
    },
    // ===== TEXAS =====
    // --- Austin (2 Google Calendars) ---
    {
      name: "Austin H3 Calendar",
      url: "austin.ah3@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "AH3",
      },
      kennelCodes: ["ah3"],
    },
    {
      name: "Keep Austin Weird H3 Calendar",
      url: "o2v8lpb3bs3kpohpi6hd0g426k@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "KAW!H3",
      },
      kennelCodes: ["kawh3"],
    },
    // --- Houston (1 Google Calendar + 1 Blogger + 2 Static Schedules) ---
    {
      name: "Houston Hash Calendar",
      url: "houstonhash@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        kennelPatterns: [
          ["Mosquito", "Mosquito H3"],
        ],
        defaultKennelTag: "Houston H3",
      },
      kennelCodes: ["h4-tx", "mosquito-h3"],
    },
    {
      name: "Brass Monkey H3 Blog",
      url: "https://teambrassmonkey.blogspot.com",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      kennelCodes: ["bmh3-tx"],
    },
    {
      name: "Mosquito H3 Static Schedule (1st Wed)",
      url: "https://www.facebook.com/groups/MosquitoH3/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Mosquito H3",
        rrule: "FREQ=MONTHLY;BYDAY=1WE",
        startTime: "18:30",
        defaultTitle: "Mosquito H3 Bimonthly Run",
        defaultLocation: "Houston, TX",
        defaultDescription: "Check the Facebook page at https://www.facebook.com/groups/MosquitoH3/ for updates on locations.",
      },
      kennelCodes: ["mosquito-h3"],
    },
    {
      name: "Mosquito H3 Static Schedule (3rd Wed)",
      url: "https://www.facebook.com/groups/MosquitoH3/#3rd-wed",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Mosquito H3",
        rrule: "FREQ=MONTHLY;BYDAY=3WE",
        startTime: "18:30",
        defaultTitle: "Mosquito H3 Bimonthly Run",
        defaultLocation: "Houston, TX",
        defaultDescription: "Check the Facebook page at https://www.facebook.com/groups/MosquitoH3/ for updates on locations.",
      },
      kennelCodes: ["mosquito-h3"],
    },
    // --- DFW (1 HTML scraper — PHP calendar covering 4 kennels) ---
    {
      name: "DFW Hash Calendar",
      url: "http://www.dfwhhh.org/calendar/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["dh3-tx", "duhhh", "noduhhh", "fwh3"],
    },
    // --- Corpus Christi (1 Google Calendar) ---
    {
      name: "Corpus Christi H3 Calendar",
      url: "c2h3hash@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "C2H3",
      },
      kennelCodes: ["c2h3"],
    },
    // ===== UPSTATE NEW YORK =====
    // --- Rochester (Google Calendar) ---
    {
      name: "Flour City H3 Google Calendar",
      url: "flourcitymismanagement@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "Flour City H3",
      },
      kennelCodes: ["flour-city"],
    },
    // --- Syracuse (HTML scraper) ---
    {
      name: "SOH4 Website",
      url: "https://www.soh4.com/trails/feed/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: { defaultKennelTag: "SOH4" },
      kennelCodes: ["soh4"],
    },
    // --- Capital District (HTML scraper) ---
    {
      name: "Halve Mein Website",
      url: "https://www.hmhhh.com/index.php?log=upcoming.con",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: { defaultKennelTag: "HMHHH" },
      kennelCodes: ["halvemein"],
    },
    // --- Ithaca (HTML scraper) ---
    {
      name: "IH3 Website Hareline",
      url: "http://ithacah3.org/hare-line/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: { defaultKennelTag: "IH3" },
      kennelCodes: ["ih3"],
    },
    // --- Buffalo (Google Calendar) ---
    {
      name: "Buffalo H3 Google Calendar",
      url: "hashinthebuff@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "Buffalo H3",
      },
      kennelCodes: ["bh3"],
    },
    // --- Hudson Valley (Meetup) ---
    {
      name: "Hudson Valley H3 Meetup",
      url: "https://www.meetup.com/Hudson-Valley-Hash-House-Harriers/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        groupUrlname: "Hudson-Valley-Hash-House-Harriers",
        kennelTag: "Hudson Valley H3",
      },
      kennelCodes: ["hvh3-ny"],
    },
    // ===== PENNSYLVANIA (outside Philly) =====
    // --- Pittsburgh (Google Calendar aggregator) ---
    {
      name: "Pittsburgh Hash Calendar",
      url: "pghhashcalendar@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "PGH H3",
      },
      kennelCodes: ["pgh-h3"],
    },
    // --- Pittsburgh (Iron City iCal feed) ---
    {
      name: "Iron City H3 iCal Feed",
      url: "https://ironcityh3.com/?post_type=tribe_events&ical=1&eventDisplay=list",
      type: "ICAL_FEED" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: {
        defaultKennelTag: "ICH3",
      },
      kennelCodes: ["ich3"],
    },
    // --- State College (Nittany Valley Google Calendar) ---
    {
      name: "Nittany Valley H3 Calendar",
      url: "55k6rnam11akkav5vljqlsc6lo@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "NVHHH",
      },
      kennelCodes: ["nvhhh"],
    },
    // --- Lehigh Valley (Google Calendar — FB is primary, calendar may be sparse) ---
    {
      name: "LVH3 Hareline Calendar",
      url: "lvh3hashflash@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 5,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "LVH3",
        descriptionSuffix: "Check the LVH3 Facebook page for the latest event details and updates: https://www.facebook.com/groups/lvh3/",
      },
      kennelCodes: ["lvh3"],
    },
    // --- Reading (Localendar iCal feed) ---
    {
      name: "Reading H3 Localendar",
      url: "https://localendar.com/public/readinghhh?style=X2",
      type: "ICAL_FEED" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: {
        defaultKennelTag: "RH3",
      },
      kennelCodes: ["rh3"],
    },
    // --- Harrisburg-Hershey (Google Calendar) ---
    {
      name: "H5 Google Calendar",
      url: "harrisburghersheyh3@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "H5",
      },
      kennelCodes: ["h5-hash"],
    },
    // ===== DELAWARE =====
    // --- Hockessin (HTML scraper) ---
    {
      name: "Hockessin H3 Website",
      url: "https://www.hockessinhash.org/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: { defaultKennelTag: "Hockessin H3" },
      kennelCodes: ["hockessin"],
    },
    // ===== VIRGINIA (outside DC metro) =====
    // --- Richmond (Calendar + Meetup) ---
    {
      name: "Richmond H3 Google Calendar",
      url: "979d12b454f944e14bd00e8d0d0c30b1109d6e5f37ec4817542ae35f86f90ae8@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: { defaultKennelTag: "RVAH3" },
      kennelCodes: ["rvah3"],
    },
    {
      name: "Richmond H3 Meetup",
      url: "https://www.meetup.com/richmond-hash-house-harriers/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: { groupUrlname: "richmond-hash-house-harriers", kennelTag: "RVAH3" },
      kennelCodes: ["rvah3"],
    },
    // --- Fort Eustis (Calendar + Meetup) ---
    {
      name: "Fort Eustis H3 Google Calendar",
      url: "ft.eustish3@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: { defaultKennelTag: "FEH3" },
      kennelCodes: ["feh3"],
    },
    {
      name: "Fort Eustis H3 Meetup",
      url: "https://www.meetup.com/FEH3-Hash/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: { groupUrlname: "FEH3-Hash", kennelTag: "FEH3" },
      kennelCodes: ["feh3"],
    },
    // --- BDSM H3 (Meetup) ---
    {
      name: "BDSM H3 Meetup",
      url: "https://www.meetup.com/BDSM-Hash-House-Harriers/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: { groupUrlname: "BDSM-Hash-House-Harriers", kennelTag: "BDSMH3" },
      kennelCodes: ["bdsmh3"],
    },
    // --- cHARLOTtesville (Meetup) ---
    {
      name: "cHARLOTtesville H3 Meetup",
      url: "https://www.meetup.com/meetup-group-xxcniptw/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: { groupUrlname: "meetup-group-xxcniptw", kennelTag: "CvilleH3" },
      kennelCodes: ["cvilleh3"],
    },
    // --- Fredericksburg (Static Schedule — kennel already exists, adding source) ---
    {
      name: "FUH3 Static Schedule",
      url: "https://www.facebook.com/groups/fuh3va/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "FUH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SA",
        anchorDate: "2026-03-08",
        startTime: "15:00",
        defaultTitle: "FUH3 Biweekly Run",
        defaultLocation: "Fredericksburg, VA",
        defaultDescription: "Check the Facebook page at https://www.facebook.com/groups/fuh3va/ for updates on locations.",
      },
      kennelCodes: ["fuh3"],
    },
    // --- Tidewater (Static Schedule — main Sunday trail only) ---
    {
      name: "Tidewater H3 Static Schedule",
      url: "https://www.facebook.com/groups/SEVAHHH",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Tidewater H3",
        rrule: "FREQ=WEEKLY;BYDAY=SU",
        startTime: "14:00",
        defaultTitle: "Tidewater H3 Weekly Run",
        defaultLocation: "Virginia Beach, VA",
        defaultDescription: "Check the Facebook page at https://www.facebook.com/groups/SEVAHHH for updates on locations and times. Times vary seasonally.",
      },
      kennelCodes: ["twh3"],
    },
    // --- Lynchburg (Static Schedule — Wednesday only) ---
    {
      name: "Seven Hills H3 Static Schedule",
      url: "https://www.facebook.com/groups/41511405734/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "7H4",
        rrule: "FREQ=WEEKLY;BYDAY=WE",
        startTime: "18:30",
        defaultTitle: "Seven Hills H3 Weekly Run",
        defaultLocation: "Lynchburg, VA",
        defaultDescription: "Check the Facebook page at https://www.facebook.com/groups/41511405734/ for updates on locations.",
      },
      kennelCodes: ["7h4"],
    },
    // ===== NORTH CAROLINA =====
    // --- Raleigh / Triangle ---
    {
      name: "SWH3 Google Calendar",
      url: "sirwaltersh3@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: { defaultKennelTag: "SWH3" },
      kennelCodes: ["swh3"],
    },
    {
      name: "SWH3 Trail Announcements",
      url: "https://swh3.wordpress.com/category/trail-announcements/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      kennelCodes: ["swh3"],
    },
    {
      name: "Carolina Larrikins Google Calendar",
      url: "3p2vupffo2qukm6ee8gg9clo3o@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: { defaultKennelTag: "Larrikins" },
      kennelCodes: ["larrikins"],
    },
    // --- Charlotte (Meetup) ---
    {
      name: "Charlotte H3 Meetup",
      url: "https://www.meetup.com/charlotte-hash-house-harriers/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: { groupUrlname: "charlotte-hash-house-harriers", kennelTag: "CH3" },
      kennelCodes: ["ch3-nc"],
    },
    // --- Asheville (Meetup) ---
    {
      name: "Asheville H3 Meetup",
      url: "https://www.meetup.com/AVLH3-On-On/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: { groupUrlname: "AVLH3-On-On", kennelTag: "AVLH3" },
      kennelCodes: ["avlh3"],
    },
    // --- Wilmington / Cape Fear (WordPress hareline page) ---
    {
      name: "Cape Fear H3 Website",
      url: "https://capefearh3.com/hare-line/",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: {
        defaultKennelTag: "CFH3",
        containerSelector: "table:first-of-type",
        rowSelector: "tr",
        columns: { runNumber: "td:nth-child(1)", date: "td:nth-child(2)", hares: "td:nth-child(3)" },
      },
      kennelCodes: ["cfh3"],
    },
    // --- Fayetteville (Meetup) ---
    {
      name: "Carolina Trash H3 Meetup",
      url: "https://www.meetup.com/fayetteville-running-training-meetup-group/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: { groupUrlname: "fayetteville-running-training-meetup-group", kennelTag: "CTrH3" },
      kennelCodes: ["ctrh3"],
    },
    // ===== FLORIDA =====
    // --- API-based sources ---
    {
      name: "Miami H3 Meetup",
      url: "https://www.meetup.com/miami-hash-house-harriers/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        groupUrlname: "miami-hash-house-harriers",
        kennelTag: "MIA H3",
      },
      kennelCodes: ["mia-h3"],
    },
    {
      name: "Key West H3 Google Calendar",
      url: "264vvpn7002rqbm1f82489fl8c@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "KWH3",
      },
      kennelCodes: ["kwh3"],
    },
    {
      name: "O2H3 Google Calendar",
      url: "hashcalendar@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "O2H3",
      },
      kennelCodes: ["o2h3"],
    },
    // --- WCFH Calendar (11 Tampa Bay kennels) ---
    {
      name: "West Central FL Hash Calendar",
      url: "https://www.jollyrogerh3.com/WCFH_Calendar.htm",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "daily",
      scrapeDays: 365,
      kennelCodes: ["barf-h3", "b2b-h3", "jrh3", "lh3-fl", "sbh3", "lush", "nsah3", "circus-h3", "sph3-fl", "tth3-fl", "tbh3-fl"],
    },
    // --- Static schedule sources ---
    {
      name: "Wildcard H3 Static Schedule",
      url: "https://www.facebook.com/groups/373426549449867/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Wildcard H3",
        rrule: "FREQ=WEEKLY;BYDAY=MO",
        anchorDate: "2026-03-02",
        startTime: "18:30",
        defaultTitle: "Wildcard H3 Weekly Run",
        defaultLocation: "Fort Lauderdale, FL",
        defaultDescription: "Weekly Monday evening trail. Check Facebook for start location.",
      },
      kennelCodes: ["wildcard-h3"],
    },
    {
      name: "H6 Static Schedule",
      url: "https://www.facebook.com/HollyweirdH6/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "H6",
        rrule: "FREQ=WEEKLY;BYDAY=FR",
        anchorDate: "2026-03-06",
        startTime: "18:30",
        defaultTitle: "H6 Weekly Run",
        defaultLocation: "Hollywood, FL",
        defaultDescription: "Weekly Friday evening trail. BYOB. Check Facebook for start location.",
      },
      kennelCodes: ["h6"],
    },
    {
      name: "PBH3 Static Schedule",
      url: "https://www.facebook.com/groups/pbhhh/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "PBH3",
        rrule: "FREQ=WEEKLY;BYDAY=WE",
        anchorDate: "2026-03-04",
        startTime: "18:30",
        defaultTitle: "PBH3 Weekly Run",
        defaultLocation: "Palm Beach County, FL",
        defaultDescription: "Weekly Wednesday trail. Check Facebook for start location.",
      },
      kennelCodes: ["pbh3"],
    },
    {
      name: "GATR H3 Static Schedule",
      url: "https://gatrh3.wordpress.com",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "GATR H3",
        rrule: "FREQ=MONTHLY;BYDAY=3SA",
        anchorDate: "2026-03-21",
        startTime: "14:00",
        defaultTitle: "GATR H3 Monthly Trail",
        defaultLocation: "Gainesville, FL",
        defaultDescription: "Monthly Saturday trail run. Check WordPress blog for start location and details.",
      },
      kennelCodes: ["gatr-h3"],
    },
    // ===== GEORGIA =====
    // --- SavH3 Meetup (already in DB — ensure kennel link + bump trustLevel) ---
    {
      name: "Savannah H3 Meetup",
      url: "https://www.meetup.com/savannah-hash-house-harriers/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        groupUrlname: "savannah-hash-house-harriers",
        kennelTag: "SavH3",
      },
      kennelCodes: ["savh3"],
    },
    // --- Atlanta Hash Board (phpBB Atom feed — 9 kennels) ---
    {
      name: "Atlanta Hash Board",
      url: "https://board.atlantahash.com",
      type: "HTML_SCRAPER" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        forums: {
          "2": { kennelTag: "AH4", hashDay: "Saturday" },
          "4": { kennelTag: "PH3", hashDay: "Saturday" },
          "5": { kennelTag: "BSH3", hashDay: "Sunday" },
          "6": { kennelTag: "SOBH3", hashDay: "Sunday" },
          "7": { kennelTag: "WHH3", hashDay: "Sunday" },
          "8": { kennelTag: "MLH4", hashDay: "Monday" },
          "9": { kennelTag: "DUFF H3", hashDay: "Wednesday" },
          "10": { kennelTag: "SLUT H3", hashDay: "Thursday" },
          "11": { kennelTag: "SoCo", hashDay: "Friday" },
        },
      },
      kennelCodes: ["ah4", "ph3-atl", "bsh3", "sobh3", "whh3", "mlh4", "duffh3", "sluth3", "soco-h3"],
    },
    // --- Georgia Static Schedule sources ---
    {
      name: "SCH3 Static Schedule",
      url: "https://board.atlantahash.com/viewforum.php?f=3",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Southern Comfort H3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=FR",
        anchorDate: "2026-03-06",
        startTime: "19:00",
        defaultTitle: "SCH3 Biweekly Run",
        defaultLocation: "Atlanta, GA",
        defaultDescription: "Alternate Friday evening trail. Check Atlanta Hash Board for details.",
      },
      kennelCodes: ["sch3-atl"],
    },
    {
      name: "HMH3 Static Schedule",
      url: "https://board.atlantahash.com#hmh3",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "HMH3",
        rrule: "FREQ=MONTHLY;BYDAY=1SU",
        anchorDate: "2026-03-01",
        startTime: "13:30",
        defaultTitle: "HMH3 Monthly Run",
        defaultLocation: "North Georgia",
        defaultDescription: "First Sunday monthly trail in the north Georgia foothills.",
      },
      kennelCodes: ["hmh3"],
    },
    {
      name: "CUNT H3 ATL Static Schedule",
      url: "https://board.atlantahash.com#cunth3",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "CUNT H3",
        rrule: "FREQ=MONTHLY;BYDAY=1TU",
        anchorDate: "2026-03-03",
        startTime: "19:00",
        defaultTitle: "CUNT H3 Monthly Run",
        defaultLocation: "Atlanta, GA",
        defaultDescription: "First Tuesday monthly evening trail in Atlanta.",
      },
      kennelCodes: ["cunth3-atl"],
    },
    {
      name: "PFH3 Static Schedule",
      url: "https://www.facebook.com/groups/peachfuzzh3",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "PFH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=WE",
        anchorDate: "2026-03-04",
        startTime: "18:30",
        defaultTitle: "PFH3 Biweekly Run",
        defaultLocation: "Augusta, GA",
        defaultDescription: "Alternate Wednesday evening trail. Check Facebook for start location.",
      },
      kennelCodes: ["pfh3"],
    },
    {
      name: "AUGH3 Static Schedule",
      url: "https://www.facebook.com/groups/augustaundergroundhash",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "AUGH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SA",
        anchorDate: "2026-03-07",
        startTime: "14:00",
        defaultTitle: "AUGH3 Biweekly Run",
        defaultLocation: "Augusta, GA",
        defaultDescription: "Alternate Saturday trail. Check Facebook for start location.",
      },
      kennelCodes: ["augh3"],
    },
    {
      name: "MGH4 Static Schedule",
      url: "https://www.facebook.com/groups/middlegeorgiahash",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "MGH4",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SA",
        anchorDate: "2026-03-07",
        startTime: "14:00",
        defaultTitle: "MGH4 Biweekly Run",
        defaultLocation: "Macon, GA",
        defaultDescription: "Alternate Saturday trail. Check Facebook for start location.",
      },
      kennelCodes: ["mgh4"],
    },
    {
      name: "W3H3 GA Static Schedule",
      url: "https://www.facebook.com/groups/w3h3macon",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Wed Wed Wed H3",
        rrule: "FREQ=WEEKLY;BYDAY=WE",
        anchorDate: "2026-03-04",
        startTime: "18:30",
        defaultTitle: "W3H3 Weekly Run",
        defaultLocation: "Macon, GA",
        defaultDescription: "Weekly Wednesday evening trail. Check Facebook for start location.",
      },
      kennelCodes: ["w3h3-ga"],
    },
    {
      name: "CVH3 Static Schedule",
      url: "https://www.facebook.com/groups/cvh3columbus",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "CVH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SA",
        anchorDate: "2026-03-07",
        startTime: "11:00",
        defaultTitle: "CVH3 Biweekly Run",
        defaultLocation: "Columbus, GA",
        defaultDescription: "Alternate Saturday morning trail. Check Facebook for start location.",
      },
      kennelCodes: ["cvh3"],
    },
    {
      name: "R2H3 Static Schedule",
      url: "https://www.facebook.com/groups/r2h3rome",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "R2H3",
        rrule: "FREQ=MONTHLY;BYDAY=2SA",
        anchorDate: "2026-03-14",
        startTime: "14:30",
        defaultTitle: "R2H3 Monthly Run",
        defaultLocation: "Rome, GA",
        defaultDescription: "Second Saturday monthly trail. Check Facebook for start location.",
      },
      kennelCodes: ["r2h3"],
    },
    // ===== SOUTH CAROLINA =====
    {
      name: "Charleston Heretics Meetup",
      url: "https://www.meetup.com/charlestonheretics/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        groupUrlname: "charlestonheretics",
        kennelTag: "CHH3",
      },
      kennelCodes: ["chh3"],
    },
    {
      name: "Charleston H3 Static Schedule",
      url: "https://www.facebook.com/groups/charlestonhash/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "Charleston H3",
        rrule: "FREQ=WEEKLY;BYDAY=TH",
        anchorDate: "2026-03-05",
        startTime: "18:30",
        defaultTitle: "CH3 Weekly Run",
        defaultLocation: "Charleston, SC",
        defaultDescription: "Weekly Thursday evening trail. Check Facebook for start location.",
      },
      kennelCodes: ["ch3-sc"],
    },
    {
      name: "BUDH3 Static Schedule",
      url: "https://www.facebook.com/groups/beaufortuglydog/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "BUDH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SA",
        anchorDate: "2026-03-07",
        startTime: "15:00",
        defaultTitle: "BUDH3 Biweekly Run",
        defaultLocation: "Beaufort, SC",
        defaultDescription: "Alternate Saturday trail. Check Facebook for start location.",
      },
      kennelCodes: ["budh3"],
    },
    {
      name: "Columbian H3 Static Schedule (1st Sunday)",
      url: "https://www.facebook.com/groups/columbianh3/#1st-sunday",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "ColH3",
        rrule: "FREQ=MONTHLY;BYDAY=1SU",
        anchorDate: "2026-03-01",
        startTime: "15:00",
        defaultTitle: "ColH3 Biweekly Run",
        defaultLocation: "Columbia, SC",
        defaultDescription: "1st & 3rd Sunday trail. Check Facebook for start location.",
      },
      kennelCodes: ["colh3"],
    },
    {
      name: "Columbian H3 Static Schedule (3rd Sunday)",
      url: "https://www.facebook.com/groups/columbianh3/#3rd-sunday",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "ColH3",
        rrule: "FREQ=MONTHLY;BYDAY=3SU",
        anchorDate: "2026-03-15",
        startTime: "15:00",
        defaultTitle: "ColH3 Biweekly Run",
        defaultLocation: "Columbia, SC",
        defaultDescription: "1st & 3rd Sunday trail. Check Facebook for start location.",
      },
      kennelCodes: ["colh3"],
    },
    {
      name: "Secession H3 Static Schedule",
      url: "https://secessionh3.wordpress.com",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "SecH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SA",
        anchorDate: "2026-03-14",
        startTime: "15:00",
        defaultTitle: "SecH3 Biweekly Run",
        defaultLocation: "Columbia, SC",
        defaultDescription: "Alternate Saturday trail. Check Facebook for start location.",
      },
      kennelCodes: ["sech3"],
    },
    {
      name: "Palmetto H3 Static Schedule",
      url: "https://www.facebook.com/PalmettoH3/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "PalH3",
        rrule: "FREQ=MONTHLY;BYDAY=3SA",
        anchorDate: "2026-03-21",
        startTime: "14:00",
        defaultTitle: "PalH3 Monthly Run",
        defaultLocation: "Sumter, SC",
        defaultDescription: "Third Saturday monthly trail. Check Facebook for start location.",
      },
      kennelCodes: ["palh3"],
    },
    {
      name: "Upstate H3 Static Schedule",
      url: "https://www.upstatehashers.com/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "UH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SU",
        anchorDate: "2026-03-08",
        startTime: "14:00",
        defaultTitle: "UH3 Biweekly Run",
        defaultLocation: "Greenville, SC",
        defaultDescription: "Alternate Sunday trail. Check website or Facebook for start location.",
      },
      kennelCodes: ["uh3"],
    },
    {
      name: "GOTH3 Static Schedule",
      url: "https://gothh3.com/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "GOTH3",
        rrule: "FREQ=MONTHLY;BYDAY=3SA",
        anchorDate: "2026-03-21",
        startTime: "14:30",
        defaultTitle: "GOTH3 Monthly Run",
        defaultLocation: "Greenville, SC",
        defaultDescription: "Third Saturday monthly trail. Casual walker/runner mix.",
      },
      kennelCodes: ["goth3"],
    },
    {
      name: "Grand Strand H3 Static Schedule",
      url: "https://www.facebook.com/GrandStrandHashing/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "GSH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=SA",
        anchorDate: "2026-03-07",
        startTime: "16:00",
        defaultTitle: "GSH3 Biweekly Run",
        defaultLocation: "Myrtle Beach, SC",
        defaultDescription: "Alternate Saturday trail. Check Facebook for start location.",
      },
      kennelCodes: ["gsh3"],
    },
    // Massachusetts
    {
      name: "Happy Valley H3 Static Schedule",
      url: "https://happyvalleyh3.org/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "HVH3",
        rrule: "FREQ=WEEKLY;INTERVAL=2;BYDAY=TH",
        startTime: "18:30",
        timezone: "America/New_York",
        defaultTitle: "HVH3 Biweekly Run",
        defaultLocation: "Western Massachusetts",
        defaultDescription: "Biweekly Thursday hash in the Pioneer Valley.",
      },
      kennelCodes: ["hvh3"],
    },
    {
      name: "PooFlingers H3 Static Schedule",
      url: "https://www.facebook.com/groups/pooflingers/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "PooFH3",
        rrule: "FREQ=MONTHLY;BYDAY=SA;BYSETPOS=3",
        startTime: "14:00",
        timezone: "America/New_York",
        defaultTitle: "PooFH3 Monthly Run",
        defaultLocation: "New England",
        defaultDescription: "Monthly 3rd Saturday hash throughout New England.",
      },
      kennelCodes: ["poofh3"],
    },
    {
      name: "Northboro H3 Website",
      url: "https://www.northboroh3.com",
      type: "HTML_SCRAPER" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      kennelCodes: ["nbh3"],
    },
    // ===== VERMONT =====
    {
      name: "Von Tramp H3 Meetup",
      url: "https://www.meetup.com/vontramph3/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: {
        groupUrlname: "vontramph3",
        kennelTag: "VTH3",
      },
      kennelCodes: ["vth3"],
    },
    {
      name: "Burlington H3 Website Hareline",
      url: "https://www.burlingtonh3.com/hareline",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      kennelCodes: ["burlyh3"],
    },
    // ===== RHODE ISLAND =====
    {
      name: "RIH3 Static Schedule",
      url: "https://rih3.com/",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 5,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        kennelTag: "RIH3",
        rrule: "FREQ=WEEKLY;BYDAY=MO",
        anchorDate: "2026-03-09",
        startTime: "18:30",
        timezone: "America/New_York",
        defaultTitle: "RIH3 Monday Trail",
        defaultLocation: "Rhode Island",
        defaultDescription: "Weekly Monday evening hash. 6:30 PM sharp.",
      },
      kennelCodes: ["rih3"],
    },
    {
      name: "RIH3 Website Hareline",
      url: "https://rih3.com/hareline.html",
      type: "HTML_SCRAPER" as const,
      trustLevel: 6,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      kennelCodes: ["rih3"],
    },
    // ===== CONNECTICUT =====
    {
      name: "Narwhal H3 Meetup (CTH3)",
      url: "https://www.meetup.com/meetup-group-cwrnpwpc/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 180,
      config: {
        groupUrlname: "meetup-group-cwrnpwpc",
        kennelTag: "Narwhal H3",
      },
      kennelCodes: ["narwhal-h3"],
    },
    // ===== OREGON =====
    // --- Oregon Hashing Calendar aggregator (OH3, TGIF, Cherry City events) ---
    {
      name: "Oregon Hashing Calendar",
      url: "cae3r4u2uhucmmi9rvq5eu6obg@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "cae3r4u2uhucmmi9rvq5eu6obg@group.calendar.google.com",
        kennelPatterns: [
          ["OH3.*Full Moon|OH3 #|OH3 -|OH3$", "OH3"],
          ["TGIF|Friday.*Pubcrawl", "TGIF"],
          ["Cherry City|Cherry Cherry City", "CCH3"],
        ],
        defaultKennelTag: "OH3",
      },
      kennelCodes: ["oh3", "tgif", "cch3-or"],
    },
    // --- Individual kennel calendars ---
    {
      name: "No Name H3 Calendar",
      url: "63h32shgrk48ci0li17lmoijeg@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "63h32shgrk48ci0li17lmoijeg@group.calendar.google.com",
        defaultKennelTag: "N2H3",
      },
      kennelCodes: ["n2h3"],
    },
    {
      name: "Kahuna H3 Calendar",
      url: "e63ac95062e8cb80b4c470e316701cfba3046903bc6662c456efe87d52250e9e@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "e63ac95062e8cb80b4c470e316701cfba3046903bc6662c456efe87d52250e9e@group.calendar.google.com",
        defaultKennelTag: "OKH3",
      },
      kennelCodes: ["okh3"],
    },
    {
      name: "Portland Humpin' Hash Calendar",
      url: "e42428cbbecf52a48618c36aa1654ec0186aa307eb6d608641ef3a9e5c243128@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "e42428cbbecf52a48618c36aa1654ec0186aa307eb6d608641ef3a9e5c243128@group.calendar.google.com",
        defaultKennelTag: "PH4",
      },
      kennelCodes: ["ph4"],
    },
    {
      name: "Stumptown H3 Calendar",
      url: "5e6c1e6bdcb70c74eb924aee3d74f63e13a65c91f86844f50b37f412a768e82c@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "5e6c1e6bdcb70c74eb924aee3d74f63e13a65c91f86844f50b37f412a768e82c@group.calendar.google.com",
        defaultKennelTag: "StumpH3",
      },
      kennelCodes: ["stumph3"],
    },
    {
      name: "Dead Whores H3 Calendar",
      url: "e435782c94f98136bde0957e4f791bdd3a0ac0d13970bbfe1ff34f5ddc676990@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "e435782c94f98136bde0957e4f791bdd3a0ac0d13970bbfe1ff34f5ddc676990@group.calendar.google.com",
        defaultKennelTag: "DWH3",
      },
      kennelCodes: ["dwh3"],
    },
    {
      name: "SWH3 Calendar",
      url: "898ddb527b83d7944c788bfbdb4074be5ee3c5ddf380acbdb206abd2861d6dc2@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "898ddb527b83d7944c788bfbdb4074be5ee3c5ddf380acbdb206abd2861d6dc2@group.calendar.google.com",
        defaultKennelTag: "Portland SWH3",
      },
      kennelCodes: ["swh3-or"],
    },
    {
      name: "Salem H3 Calendar",
      url: "0f125fcba18bfeca585fe7d3592c70159df9c97d620dfd68fd65a73fcd063d8c@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "0f125fcba18bfeca585fe7d3592c70159df9c97d620dfd68fd65a73fcd063d8c@group.calendar.google.com",
        defaultKennelTag: "SalemH3",
      },
      kennelCodes: ["salemh3"],
    },
    {
      name: "Cherry City H3 Calendar",
      url: "711a1cfbec0cfbcc26ba28c79d943700e6b7c33c8c11896a86da701fc96291b6@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "711a1cfbec0cfbcc26ba28c79d943700e6b7c33c8c11896a86da701fc96291b6@group.calendar.google.com",
        defaultKennelTag: "CCH3",
      },
      kennelCodes: ["cch3-or"],
    },
    {
      name: "Eugene H3 Calendar",
      url: "8b593752049f42f9aca8fb04197bfb25d7f4148db8c314991e842bbf6b4ea303@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "8b593752049f42f9aca8fb04197bfb25d7f4148db8c314991e842bbf6b4ea303@group.calendar.google.com",
        defaultKennelTag: "Eugene H3",
      },
      kennelCodes: ["eh3-or"],
    },
    {
      name: "Central Oregon H3 Calendar",
      url: "6ureum96qhgf13kj820i61ovq8@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        calendarId: "6ureum96qhgf13kj820i61ovq8@group.calendar.google.com",
        defaultKennelTag: "COH3",
      },
      kennelCodes: ["coh3"],
    },
    // ===== WASHINGTON =====
    // --- WA Hash Google Calendar (multi-kennel aggregator) ---
    {
      name: "WA Hash Google Calendar",
      url: "8d65om7lrdq538ksqednh2n648@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelPatterns: [
          ["^SH3\\b|Seattle H3", "SH3"],
          ["^PSH3\\b|Puget Sound", "PSH3"],
          ["^NBH3\\b|No Balls", "NBH3"],
          ["^RCH3\\b|Rain City", "Rain City H3"],
          ["SeaMon", "SeaMon"],
          ["^TH3\\b|Tacoma H3|^Tacoma", "Tacoma H3"],
          ["^SSH3\\b|South Sound", "SSH3"],
          ["CUNTh", "CUNTh"],
          ["Taint", "Taint"],
          ["Giggity", "Giggity"],
          ["South End|^SEH3|^SEH5", "SEH3"],
          ["HSWTF", "HSWTF"],
          ["Leap Year", "Leap Year"],
        ],
        defaultKennelTag: "SH3",
      },
      kennelCodes: ["sh3-wa", "psh3", "nbh3-wa", "rch3-wa", "seamon-h3", "th3-wa", "ssh3-wa", "cunth3-wa", "taint-h3", "giggity-h3", "seh3-wa", "hswtf-h3", "leapyear-h3"],
    },
    // --- Per-kennel Google Sheets (secondary enrichment) ---
    {
      name: "Seattle H3 Hareline Sheet",
      url: "https://docs.google.com/spreadsheets/d/1rTa69Z12V4EAdlRGToOiMIIiFiTbqZFN653hs5DwALk",
      type: "GOOGLE_SHEETS" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      config: {
        sheetId: "1rTa69Z12V4EAdlRGToOiMIIiFiTbqZFN653hs5DwALk",
        gid: 0,
        skipRows: 0,
        tabs: ["Sheet1"],
        columns: { runNumber: 0, date: 1, hares: 2, title: 3, location: 4, description: 5 },
        kennelTagRules: { default: "SH3" },
      },
      kennelCodes: ["sh3-wa"],
    },
    {
      name: "Puget Sound H3 Hareline Sheet",
      url: "https://docs.google.com/spreadsheets/d/1XTN-ivc5NClSt4Z1HVYf0ddEzF3aXcnd1ZH0JFpLXm4",
      type: "GOOGLE_SHEETS" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      config: {
        sheetId: "1XTN-ivc5NClSt4Z1HVYf0ddEzF3aXcnd1ZH0JFpLXm4",
        gid: 237970172,
        skipRows: 2,
        columns: { runNumber: 0, date: 2, hares: 3, title: 4, location: -1 },
        kennelTagRules: { default: "PSH3" },
      },
      kennelCodes: ["psh3"],
    },
    // No Balls H3 Hareline Sheet — DISABLED: sheet is private (401), no 2025/2026 data entered.
    // NBH3 events come through via the shared WA Hash Google Calendar instead.
    // Re-enable if sheet owner makes it publicly viewable.
    {
      name: "Rain City H3 Hareline Sheet",
      url: "https://docs.google.com/spreadsheets/d/1UOzHLGytOdlzjet7VE25gXAMcuU4oc8fi8gY-4cQUkA",
      type: "GOOGLE_SHEETS" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      config: {
        sheetId: "1UOzHLGytOdlzjet7VE25gXAMcuU4oc8fi8gY-4cQUkA",
        gid: 0,
        skipRows: 2,
        columns: { runNumber: 0, date: 1, hares: 2, title: 3, location: -1 },
        kennelTagRules: { default: "Rain City H3" },
      },
      kennelCodes: ["rch3-wa"],
    },
    {
      name: "SeaMon H3 Hareline Sheet",
      url: "https://docs.google.com/spreadsheets/d/12Ajped8oyheVayDmHs0d8glLVo23VOg8gRKCe4yQP-g",
      type: "GOOGLE_SHEETS" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      config: {
        sheetId: "12Ajped8oyheVayDmHs0d8glLVo23VOg8gRKCe4yQP-g",
        gid: 0,
        skipRows: 1,
        columns: { runNumber: 0, date: 1, hares: 2, title: 3, location: -1 },
        kennelTagRules: { default: "SeaMon" },
      },
      kennelCodes: ["seamon-h3"],
    },
    {
      name: "Leap Year H3 Hareline Sheet",
      url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ_z30ZkQNOwcAka4qU22bAGYIVjJFc5NyICst9OeUWPvi27lNK8ICkZllzLI0gjLwQDjVvlt3mMlDM/pub",
      type: "GOOGLE_SHEETS" as const,
      trustLevel: 5,
      scrapeFreq: "weekly",
      scrapeDays: 800,
      config: {
        sheetId: "anonymous",
        csvUrl: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ_z30ZkQNOwcAka4qU22bAGYIVjJFc5NyICst9OeUWPvi27lNK8ICkZllzLI0gjLwQDjVvlt3mMlDM/pub?output=csv",
        skipRows: 2,
        columns: { runNumber: 0, date: 1, hares: 2, title: 3, location: -1 },
        kennelTagRules: { default: "Leap Year" },
      },
      kennelCodes: ["leapyear-h3"],
    },
    // ===== COLORADO =====
    // --- Denver H3 (Google Calendar) ---
    {
      name: "Denver H3 Google Calendar",
      url: "denverkennel@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "DH3" },
      kennelCodes: ["dh3-co"],
    },
    // --- Mile High Humpin' Hash (Google Calendar) ---
    {
      name: "Mile High Humpin Hash Calendar",
      url: "huhahareraiser@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "MiHiHuHa" },
      kennelCodes: ["mihi-huha"],
    },
    // --- Colorado H3 Aggregator (Google Calendar — covers Boulder H3 + others) ---
    {
      name: "Colorado H3 Aggregator Calendar",
      url: "v94tqngukqr5cdffg9q7rruvl0@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelPatterns: [
          ["Boulder H3|^BH3", "BH3"],
          ["MiHiHuHa|MiHiHUHa", "MiHiHuHa"],
        ],
        defaultKennelTag: "BH3",
      },
      kennelCodes: ["bh3-co", "mihi-huha"],
    },
    // --- Fort Collins H3 (Google Calendar) ---
    {
      name: "Fort Collins H3 Google Calendar",
      url: "fc8df0937002479306c3fed0055fb7273cb62a46abe5c7f652e3e318310f9143@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "Fort Collins H3" },
      kennelCodes: ["fch3-co"],
    },
    // --- Colorado Springs H3 (Google Calendar — multi-kennel) ---
    {
      name: "Colorado Springs H3 Calendar",
      url: "cspringsh3@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelPatterns: [
          ["^PPH4|Pikes Peak", "PPH4"],
          ["^Kimchi", "Kimchi"],
          ["^DIM", "DIM"],
        ],
        defaultKennelTag: "PPH4",
      },
      kennelCodes: ["pph4", "kimchi-h3", "dim-h3"],
    },
    // ===== MINNESOTA =====
    {
      name: "Minneapolis H3 Calendar",
      url: "minneapolishash@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelPatterns: [
          ["\\bT3H3\\b|Twin Titties", "T3H3"],
          ["\\bMH3\\b", "MH3"]
        ],
        defaultKennelTag: "MH3",
      },
      kennelCodes: ["mh3-mn", "t3h3"],
    },
    // ===== ARIZONA =====
    // --- Phoenix (iCal Feed — multi-kennel) ---
    {
      name: "Phoenix H3 Events",
      url: "https://www.phoenixhhh.org/?plugin=events-manager&page=events.ics",
      type: "ICAL_FEED" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelPatterns: [
          ["^LBH\\b|Lost Boobs", "LBH"],
          ["Hump D", "Hump D"],
          ["Wrong Way", "Wrong Way"],
          ["Dusk.*Down|FDTDD", "FDTDD"],
        ],
        defaultKennelTag: "Wrong Way",
      },
      kennelCodes: ["lbh-phx", "hump-d", "wrong-way", "fdtdd"],
    },
    // --- Phoenix (HTML Scraper — Big Ass Calendar) ---
    {
      name: "Phoenix H3 Big Ass Calendar",
      url: "https://www.phoenixhhh.org/?page_id=21",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "weekly",
      scrapeDays: 365,
      config: {
        kennelPatterns: [
          ["^LBH\\b|Lost Boobs", "LBH"],
          ["Hump D", "Hump D"],
          ["Wrong Way", "Wrong Way"],
          ["Dusk.*Down|FDTDD", "FDTDD"],
        ],
        defaultKennelTag: "Wrong Way",
      },
      kennelCodes: ["lbh-phx", "hump-d", "wrong-way", "fdtdd"],
    },
    // --- Tucson (Google Calendar — per-kennel) ---
    {
      name: "jHavelina H3 Google Calendar",
      url: "jhavelinahhh@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "jHav" },
      kennelCodes: ["jhav-h3"],
    },
    {
      name: "Mr. Happy's H3 Google Calendar",
      url: "mrhappyshhh@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "Mr. Happy's" },
      kennelCodes: ["mrhappy"],
    },
    {
      name: "Pedal Files Bash Google Calendar",
      url: "tucsonhhh@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "Pedal Files" },
      kennelCodes: ["pedalfiles"],
    },
    // ===== CALIFORNIA =====
    // --- Santa Cruz (Static Schedule) ---
    {
      name: "Surf City H3 Static Schedule",
      url: "https://www.sch3.net",
      type: "STATIC_SCHEDULE" as const,
      trustLevel: 3,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelTag: "SCH3",
        rrule: "FREQ=WEEKLY;BYDAY=TH",
        startTime: "18:30",
        timezone: "America/Los_Angeles",
        defaultTitle: "SCH3 Weekly Thursday Hash",
        defaultLocation: "Santa Cruz, CA — check Facebook for details",
        defaultDescription: "Weekly Thursday evening hash in Santa Cruz.",
      },
      kennelCodes: ["sch3-ca"],
    },
    // --- Los Angeles Area (Google Calendar) ---
    {
      name: "LAH3 Google Calendar",
      url: "hash.org_8er4h3q5qct5apu9nl2v7ic4c0@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "LAH3" },
      kennelCodes: ["lah3"],
    },
    {
      name: "LBH3 Google Calendar",
      url: "hash.org_apdt0s7aam1mdl1ckc4n1rcc4k@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "LBH3" },
      kennelCodes: ["lbh3"],
    },
    {
      name: "TDH3 Google Calendar",
      url: "hash.org_efk2ibem9h2lonqgignpcp8uoo@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "TDH3" },
      kennelCodes: ["tdh3-lb"],
    },
    {
      name: "GAL Google Calendar",
      url: "hash.org_vca9alu5cu5q2hkvip31fma6so@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "GAL" },
      kennelCodes: ["gal-h3"],
    },
    {
      name: "SUPH3 Google Calendar",
      url: "c_95c7557021b96e1c88a6df5a9132ac59082e1bfc2c2ba3eb4dc7f70b84155caa@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "SUPH3" },
      kennelCodes: ["suph3"],
    },
    {
      name: "Foothill H3 Google Calendar",
      url: "hash.org_6ocimc04ghdh7652dlvnjs5060@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "FtH3" },
      kennelCodes: ["fth3"],
    },
    {
      name: "East LA H3 Google Calendar",
      url: "hash.org_t92ud36ad0jbao70f22d2eptuc@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "ELAH3" },
      kennelCodes: ["elah3"],
    },
    {
      name: "Signal Hill H3 Google Calendar",
      url: "hash.org_t8of6q45k4cki650d97m0b80dc@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "SGH3" },
      kennelCodes: ["sgh3"],
    },
    // --- Orange County (Google Calendar) ---
    {
      name: "OCHHH Google Calendar",
      url: "hash.org_gr8mpprvpgpiihhkfj0dd0ic4k@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "OCHHH" },
      kennelCodes: ["ochhh"],
    },
    {
      name: "OC Hump Google Calendar",
      url: "hash.org_8jis0j5k0hanmgq2c6inrf93ho@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "OC Hump" },
      kennelCodes: ["ochump"],
    },
    // --- Central Coast (Google Calendar) ---
    {
      name: "SLOH3 Google Calendar",
      url: "blj7esp5ns5sbirko1p7amr4ig@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: { defaultKennelTag: "SLOH3" },
      kennelCodes: ["sloh3"],
    },
    // --- San Diego (HTML Scraper) ---
    {
      name: "SDH3 Hareline",
      url: "https://sdh3.com/hareline.shtml",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "weekly",
      scrapeDays: 90,
      config: {
        kennelCodeMap: {
          "SDH3": "SDH3", "CLH3": "CLH3", "LJH3": "LJH3",
          "NCH3": "NCH3", "IRH3": "IRH3", "H4": "Humpin'",
          "FMH3": "FMH3", "HAH3": "HAH3", "MH4": "MH4",
          "DRH3": "DRH3",
        },
        kennelNameMap: {
          "San Diego": "SDH3", "Larrikins": "CLH3", "La Jolla": "LJH3",
          "North County": "NCH3", "Iron Rule": "IRH3", "Humpin": "Humpin'",
          "Full Moon": "FMH3", "Half-Assed": "HAH3", "Mission Harriettes": "MH4",
          "Diaper Rash": "DRH3",
        },
        includeHistory: true,
      },
      kennelCodes: ["sdh3", "clh3-sd", "ljh3", "nch3-sd", "irh3-sd", "humpin-sd", "fmh3-sd", "hah3-sd", "mh4-sd", "drh3-sd"],
    },
    // ===== OHIO =====
    // --- Cleveland (Meetup) ---
    {
      name: "Cleveland H4 Meetup",
      url: "https://www.meetup.com/cleveland-hash-house-harriers-and-harriettes/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        groupUrlname: "cleveland-hash-house-harriers-and-harriettes",
        kennelTag: "CleH4",
      },
      kennelCodes: ["cleh4"],
    },
    // --- Akron (Meetup) ---
    {
      name: "Rubber City H3 Meetup",
      url: "https://www.meetup.com/rubber-city-hash-house-harriers-and-harriettes/",
      type: "MEETUP" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 90,
      config: {
        groupUrlname: "rubber-city-hash-house-harriers-and-harriettes",
        kennelTag: "RCH3",
      },
      kennelCodes: ["rch3"],
    },
    // --- Dayton (Google Calendar) ---
    {
      name: "DH4 Google Calendar",
      url: "daytonhash@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "DH4",
      },
      kennelCodes: ["dh4"],
    },
    {
      name: "MVH3 Google Calendar",
      url: "mvh3calendar@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "Miami Valley H3",
      },
      kennelCodes: ["mvh3-day"],
    },
    {
      name: "SWOT Google Calendar",
      url: "swoth3@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "SWOT",
      },
      kennelCodes: ["swot-h3"],
    },
    // --- Cincinnati (Google Calendar) ---
    {
      name: "SCH4 Google Calendar",
      url: "sch4calendar@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "SCH4",
      },
      kennelCodes: ["sch4"],
    },
    {
      name: "QCH4 Google Calendar",
      url: "jjfn26n873ro3qi1ckobikroso@group.calendar.google.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "QCH4",
      },
      kennelCodes: ["qch4"],
    },
    {
      name: "LVH3 Google Calendar",
      url: "lickingvalleyh3@gmail.com",
      type: "GOOGLE_CALENDAR" as const,
      trustLevel: 7,
      scrapeFreq: "daily",
      scrapeDays: 365,
      config: {
        defaultKennelTag: "Licking Valley H3",
      },
      kennelCodes: ["lvh3-cin"],
    },
    // --- Columbus (Renegade H3 website) ---
    {
      name: "Renegade H3 Website",
      url: "https://www.renegadeh3.com/events",
      type: "HTML_SCRAPER" as const,
      trustLevel: 8,
      scrapeFreq: "daily",
      scrapeDays: 90,
      kennelCodes: ["renh3"],
    },
  ];

